# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_add_paiement_model"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Paiement", "verbose_name_plural": "Paiements"},
        ),
        migrations.AlterModelOptions(
            name="payout",
            options={"verbose_name": "Versement", "verbose_name_plural": "Versements"},
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="XOF", max_length=10, verbose_name="Devise"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payé le"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("mobile_money", "Mobile Money"),
                    ("card", "Carte"),
                    ("wallet", "Wallet"),
                    ("transfer", "Virement"),
                ],
                max_length=30,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_reference",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Référence paiement"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom fournisseur"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("authorized", "Autorisé"),
                    ("paid", "Payé"),
                    ("failed", "Échoué"),
                    ("refunded", "Remboursé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="payout",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="payout",
            name="currency",
            field=models.CharField(default="XOF", max_length=10, verbose_name="Devise"),
        ),
        migrations.AlterField(
            model_name="payout",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payé le"),
        ),
        migrations.AlterField(
            model_name="payout",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("scheduled", "Programmé"),
                    ("paid", "Payé"),
                    ("failed", "Échoué"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
