# Generated by Django 5.0.7 on 2026-08-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_alter_orderpaymentevent_channel"),
        ("payments", "0002_add_paiement_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("late_cancellation", "Annulation tardive"),
                            ("adjustment", "Ajustement"),
                            ("other", "Autre"),
                        ],
                        max_length=40,
                        verbose_name="Type de créance",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "À payer"),
                            ("paid", "Payée"),
                            ("waived", "Remise / abandonnée"),
                            ("canceled", "Annulée"),
                        ],
                        db_index=True,
                        default="due",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="Motif"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Clé d'idempotence"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payée le"
                    ),
                ),
                (
                    "waived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Abandonnée le"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_charges",
                        to="orders.customer",
                        verbose_name="Client",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_charges",
                        to="orders.order",
                        verbose_name="Commande source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créance client",
                "verbose_name_plural": "Créances clients",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["customer", "status"], name="pay_charge_customer_status"
                    ),
                    models.Index(
                        fields=["order", "charge_type"], name="pay_charge_order_type"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customercharge",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="customercharge_amount_gt_zero"
            ),
        ),
    ]
