# Generated by Django 5.0.7 on 2026-03-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0056_orderitem_service_type_alter_serviceitem_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("pickup_from_customer", "Collecte client"),
                            ("dropoff_to_partner", "Dépôt partenaire"),
                            ("pickup_from_partner", "Récupération partenaire"),
                            ("deliver_to_customer", "Livraison client"),
                            ("return_mission", "Retour"),
                            ("internal_transfer", "Transfert interne"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assignée"),
                            ("accepted", "Acceptée"),
                            ("en_route", "En route"),
                            ("arrived", "Arrivée"),
                            ("in_progress", "En cours"),
                            ("awaiting_validation", "En attente de validation"),
                            ("completed", "Terminée"),
                            ("failed", "Échouée"),
                            ("issue_reported", "Incident signalé"),
                        ],
                        default="assigned",
                        max_length=30,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("planned_start_at", models.DateTimeField(blank=True, null=True)),
                ("planned_end_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normale"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("sequence_index", models.PositiveIntegerField(default=1)),
                (
                    "destination_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_missions",
                        to="core.address",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v2_missions",
                        to="orders.order",
                    ),
                ),
                (
                    "source_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_missions",
                        to="core.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("started", "Démarrée"),
                            ("arrived", "Arrivée"),
                            ("collected", "Collecté"),
                            ("handed_over", "Remis"),
                            ("otp_verified", "OTP vérifié"),
                            ("photo_added", "Photo ajoutée"),
                            ("issue_reported", "Incident signalé"),
                            ("completed", "Terminée"),
                        ],
                        max_length=30,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="logistics.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
