# Generated by Django 5.0.7 on 2026-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_missionotp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="missionotp",
            old_name="verification_sid",
            new_name="message_sid",
        ),
        migrations.AddField(
            model_name="missionotp",
            name="otp_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="missionotp",
            name="provider",
            field=models.CharField(default="twilio_messaging", max_length=30),
        ),
    ]
