# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0006_missionpdfsendlog"),
        ("orders", "0071_add_paiement_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={"verbose_name": "Mission", "verbose_name_plural": "Missions"},
        ),
        migrations.AlterModelOptions(
            name="missionactionlog",
            options={
                "verbose_name": "Log de mission",
                "verbose_name_plural": "Logs de missions",
            },
        ),
        migrations.AlterField(
            model_name="mission",
            name="code",
            field=models.CharField(max_length=30, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="mission",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="v2_missions",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assignée"),
                    ("accepted", "Acceptée"),
                    ("en_route", "En route"),
                    ("arrived", "Arrivée"),
                    ("in_progress", "En cours"),
                    ("awaiting_validation", "En attente de validation"),
                    ("completed", "Terminée"),
                    ("failed", "Échouée"),
                    ("issue_reported", "Incident signalé"),
                ],
                default="assigned",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="missionactionlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="missionactionlog",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AlterField(
            model_name="missionactionlog",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="missionactionlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
