# Generated by Django 5.0.7 on 2026-08-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_add_paiement_model"),
        ("services", "0004_serviceexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="service_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="services.serviceexecution",
                verbose_name="Exécution de service",
            ),
        ),
    ]
