# Generated by Django 5.0.7 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0009_proofofdelivery_service_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Annulée le"
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assignée"),
                    ("accepted", "Acceptée"),
                    ("en_route", "En route"),
                    ("arrived", "Arrivée"),
                    ("in_progress", "En cours"),
                    ("awaiting_validation", "En attente de validation"),
                    ("completed", "Terminée"),
                    ("failed", "Échouée"),
                    ("canceled", "Annulée"),
                    ("issue_reported", "Incident signalé"),
                ],
                default="assigned",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="missionactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("started", "Démarrée"),
                    ("arrived", "Arrivée"),
                    ("collected", "Collecté"),
                    ("handed_over", "Remis"),
                    ("otp_verified", "OTP vérifié"),
                    ("photo_added", "Photo ajoutée"),
                    ("issue_reported", "Incident signalé"),
                    ("completed", "Terminée"),
                    ("canceled", "Annulée"),
                ],
                max_length=30,
            ),
        ),
    ]
