BEGIN;
INSERT INTO orders_customer (id, name, phone, address) VALUES (1, 'DIANE', '0989876765', 'COCODY') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (3, 'BABa', '0899999999', 'Cocody Angré 8ème tranche, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (4, 'TEST3', '0000000003', 'plateau avenue chardy') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (5, 'bamba', '0756247600', 'Adjame') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (6, 'Client A', '0700000004', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (7, 'Parrain1', '0999989796', 'yopougon') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (8, 'Client Test', '0807060504', 'Adjamé') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (9, 'Client Démo 5', '0505050505', 'Riviera 2') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (10, 'Client Démo 1', '0101010101', 'Cocody Angré') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (11, 'Client Démo 2', '0202020202', 'Plateau') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (12, 'Client Démo 4', '0404040404', 'Marcory') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (13, 'ISmael Konan', '0900000000', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (14, 'Client Démo 3', '0303030303', 'Yopougon') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (15, 'Client Test Assignation', '0707070707', 'Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (16, 'Client Express', '0707007070', 'Cocody Riviera 3') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (17, 'franck fany', '0099887766', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (18, 'KANGAHLE BERGER', '0707000070', 'Coco service, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (20, 'dagani', '0908070605', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (21, 'desiee', '2722476066', 'Yopougon Maroc canari, Yopougon, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (23, 'CLIENT A', '0011223344', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (24, 'Client B', '0121212121', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (31, 'Client N3 Full Demo', '0700000011', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (32, 'Client MLM Réel', '0700009999', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (33, 'Client MLM Check', '0799999999', 'Cocody Angré 8ème tranche, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (34, 'Client MLM Prod', '0700999988', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (35, 'CLIENT DEMO AFFILIÉ', '0700007777', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (36, 'Désiré Tongbé', '0748643892', 'Rue des Bourgades, Roussillon, Apt, Vaucluse, Provence-Alpes-Côte d''Azur, France métropolitaine, 84220, France') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (37, 'CLIENT YEAR DEMO MLM', '0700008888', 'Cocody – Démo MLM') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (38, 'FAbrice zagbaou', '0112121212', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (39, 'TEST2', '0110101010', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (40, 'desiee', '2722', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (41, 'TEST DISTANCE METRIX', '0100000005', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (42, 'TEST2', '0110', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (43, 'TEST9', '000000009', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (44, 'TEST10 DEZ', '0115000000', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (45, 'Dosse Doesse', '0505050606', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (47, 'Client Test', '0701010101', 'Cocody Riviera') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (48, 'jacqques Vennard', '0999988609', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (49, 'Parrain Test MLM', '0799999000', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (50, 'Client MLM Check', '0799999001', 'Cocody CITÉ BNETD, Faya, Esai, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (51, 'Affilié N1 YEARDEMO', '0700001000', 'Client technique YEARDEMO N1') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (52, 'Affilié N2 YEARDEMO', '0700002000', 'Client technique YEARDEMO N2') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (53, 'Filleul 2 MLM', '0799999002', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (54, 'TOP N3', '0799999100', 'Cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (55, 'N2', '0799999101', 'Yopougon') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (56, 'N1', '0799999102', 'Marcory') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (57, 'FILLEUL N1-N2-N3', '0799999103', 'Treichville') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (62, 'Client Test', '01020304', 'Abidjan') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (63, 'Client Test', '0700000000', 'Riviera 3, Résidence Les Lauriers 1, Villa 44') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (64, 'Blaise TITI', '0798989898', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (65, 'DEZ', '0115101010', 'Cocody blockhaus, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (66, 'Débate Der', '0990909090', 'Deux Plateaux Sococé, Rue K131, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (67, 'Fataloi Cruip', '0788888888', 'Deux Plateaux Sococé, Rue K131, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (68, 'Fabrice bla', '0798970000', 'Plateau Dokoui, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (69, 'biscuit chocolate', '0788989999', 'Riviera 3 l''ardoise, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (70, 'Flore Aimée', '0815151515', '44 Rue le Clusia, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (71, 'balibali biser', '0599999999', 'Riviéra 3, Abidjan, Côte d''Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (72, 'Client Test', '00000000', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (73, 'CLIENT PILOTE', '01010101', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (74, 'TEST', '0700000001', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (75, 'T', '0700000099', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (76, 'T2', '0700000100', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (77, 'T3', '0700000101', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (78, 'T4', '0700000102', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (79, 'T5', '0700000103', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (80, 'T6', '0700000200', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (81, 'T7', '0700000300', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (82, 'C', '0700000999', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (83, 'C', '0721959225', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (84, 'zaza', '0748633892', 'cocody') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (85, 'TEST FAGNI', '0708963511', '53, Rue Yao Georges M''bra, Riviera 3, Riviéra 3, Cocody, Abidjan, Côte d’Ivoire') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (86, 'Parrain VFINAL', '0711111111', '') ON CONFLICT DO NOTHING;
INSERT INTO orders_customer (id, name, phone, address) VALUES (87, 'Filleul VFINAL', '0722222222', '') ON CONFLICT DO NOTHING;
COMMIT;