# Generated by Django 5.0.7 on 2026-05-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Adresse", "verbose_name_plural": "Adresses"},
        ),
        migrations.AlterModelOptions(
            name="mediaasset",
            options={"verbose_name": "Média", "verbose_name_plural": "Médias"},
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(blank=True, max_length=120, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(upload_to="media_assets/", verbose_name="Fichier"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
