# Generated by Django 5.0.7 on 2026-09-01 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrowdSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crowd_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Active le matching Crowd dans le dispatch",
                        verbose_name="Module Crowd activé",
                    ),
                ),
                (
                    "crowd_pickup_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=400,
                        help_text="Montant versé au cotransporteur pour une jambe pickup",
                        max_digits=8,
                        verbose_name="Rémunération pickup Crowd (FCFA)",
                    ),
                ),
                (
                    "crowd_return_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=400,
                        help_text="Montant versé au cotransporteur pour une jambe return",
                        max_digits=8,
                        verbose_name="Rémunération return Crowd (FCFA)",
                    ),
                ),
                (
                    "crowd_minimum_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=200,
                        help_text="Montant plancher pour toute mission Crowd",
                        max_digits=8,
                        verbose_name="Rémunération minimale (FCFA)",
                    ),
                ),
                (
                    "crowd_max_detour_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Plafond global pour le détour accepté",
                        max_digits=5,
                        verbose_name="Détour max global (km)",
                    ),
                ),
                (
                    "crowd_acceptance_timeout_seconds",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Durée avant expiration d'une offre de mission",
                        verbose_name="Timeout d'acceptation (secondes)",
                    ),
                ),
                (
                    "crowd_min_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Score minimum pour qu'un cotransporteur soit éligible",
                        max_digits=5,
                        verbose_name="Score minimum requis",
                    ),
                ),
                (
                    "crowd_priority_over_pro",
                    models.BooleanField(
                        default=True,
                        help_text="Si True, le matching tente Crowd avant les livreurs pros",
                        verbose_name="Crowd prioritaire sur pro",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Crowd",
                "verbose_name_plural": "Configuration Crowd",
            },
        ),
        migrations.CreateModel(
            name="Cotransporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de contact (peut différer du compte user)",
                        max_length=20,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le cotransporteur peut recevoir des offres de mission",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Identité et documents vérifiés par OPS",
                        verbose_name="Vérifié",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("moto", "Moto"),
                            ("car", "Voiture"),
                            ("bike", "Vélo"),
                            ("foot", "À pied"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de véhicule",
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Capacité maximale de chargement",
                        max_digits=6,
                        verbose_name="Capacité (kg)",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Score 0-100 basé sur l'historique (missions réussies, retards, etc.)",
                        max_digits=5,
                        verbose_name="Score de fiabilité",
                    ),
                ),
                (
                    "total_trips",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total missions proposées"
                    ),
                ),
                (
                    "successful_trips",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Missions réussies"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotransporter_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotransporteur",
                "verbose_name_plural": "Cotransporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CotransporterRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude origine"
                    ),
                ),
                (
                    "origin_lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude origine"
                    ),
                ),
                (
                    "origin_label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Domicile - Cocody'",
                        max_length=255,
                        verbose_name="Libellé origine",
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Latitude destination",
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Longitude destination",
                    ),
                ),
                (
                    "destination_label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Travail - Plateau'",
                        max_length=255,
                        verbose_name="Libellé destination",
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        help_text="Heure à laquelle le cotransporteur quitte l'origine",
                        verbose_name="Heure de départ",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée estimée"
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'mon,tue,wed,thu,fri' (vide = trajet unique)",
                        max_length=20,
                        verbose_name="Jours de récurrence",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Valide à partir du",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Vide = pas de date de fin",
                        null=True,
                        verbose_name="Valide jusqu'au",
                    ),
                ),
                (
                    "max_detour_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Distance maximale que le cotransporteur accepte de dévier",
                        max_digits=5,
                        verbose_name="Détour max accepté (km)",
                    ),
                ),
                (
                    "time_window_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Flexibilité sur l'heure de prise en charge",
                        verbose_name="Fenêtre de tolérance (minutes)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="La route est visible pour le matching",
                        verbose_name="Route active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cotransporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="crowd.cotransporter",
                        verbose_name="Cotransporteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route cotransporteur",
                "verbose_name_plural": "Routes cotransporteurs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["origin_lat", "origin_lng"],
                        name="crowd_cotra_origin__a9ffc2_idx",
                    ),
                    models.Index(
                        fields=["destination_lat", "destination_lng"],
                        name="crowd_cotra_destina_1ba6dd_idx",
                    ),
                    models.Index(
                        fields=["is_active", "cotransporter"],
                        name="crowd_cotra_is_acti_e382f7_idx",
                    ),
                ],
            },
        ),
    ]
