# Generated by Django 5.0.7 on 2026-03-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0056_orderitem_service_type_alter_serviceitem_code"),
        ("partners", "0007_remove_deliverypartner_user"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote_type",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimatif"),
                            ("revised", "Révisé"),
                            ("final", "Final"),
                        ],
                        default="estimated",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "logistics_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="XOF", max_length=10)),
                ("is_final", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_quotes_v2",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("per_item", "Par article"),
                            ("per_kg", "Par kilo"),
                            ("fixed_fee", "Frais fixes"),
                            ("express_surcharge", "Majoration express"),
                            ("zone_surcharge", "Majoration zone"),
                            ("discount", "Remise"),
                            ("service_fee", "Frais service"),
                            ("commission", "Commission"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_rules_v2",
                        to="partners.laundrypartner",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
