# Generated by Django 5.0.7 on 2026-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("small", "Petit sac"),
                            ("medium", "Sac moyen"),
                            ("large", "Grand sac"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix prestation (FCFA)",
                    ),
                ),
                (
                    "estimated_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre estimé de pièces"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notes internes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Règle pricing sac",
                "verbose_name_plural": "Règles pricing sac",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
