# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_add_paiement_model"),
        ("partners", "0008_add_wave_number"),
        ("pricing", "0002_bagpricingrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricequote",
            options={"verbose_name": "Devis", "verbose_name_plural": "Devis"},
        ),
        migrations.AlterModelOptions(
            name="pricingrule",
            options={
                "verbose_name": "Règle de prix",
                "verbose_name_plural": "Règles de prix",
            },
        ),
        migrations.AlterField(
            model_name="pricequote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="pricequote",
            name="currency",
            field=models.CharField(default="XOF", max_length=10, verbose_name="Devise"),
        ),
        migrations.AlterField(
            model_name="pricequote",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="pricequote",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_quotes_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="pricequote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="label",
            field=models.CharField(max_length=150, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_rules_v2",
                to="partners.laundrypartner",
                verbose_name="Partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
