# Generated by Django 5.0.7 on 2025-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville / Zone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('vehicle_type', models.CharField(blank=True, choices=[('moto', 'Moto'), ('car', 'Voiture'), ('bike', 'Vélo'), ('other', 'Autre')], max_length=20, verbose_name='Type de véhicule')),
            ],
            options={
                'verbose_name': 'Livreur partenaire',
                'verbose_name_plural': 'Livreurs partenaires',
            },
        ),
        migrations.CreateModel(
            name='LaundryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville / Zone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Blanchisserie partenaire',
                'verbose_name_plural': 'Blanchisseries partenaires',
            },
        ),
    ]
