# Generated by Django 5.0.7 on 2026-02-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_deliverypartner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='user',
        ),
    ]
