# Generated by Django 5.0.7 on 2026-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_remove_deliverypartner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="wave_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numéro Wave"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="wave_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numéro Wave"
            ),
        ),
        migrations.AddField(
            model_name="relaypointpartner",
            name="wave_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numéro Wave"
            ),
        ),
    ]
