# Generated by Django 5.0.7 on 2026-05-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_add_wave_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="remuneration_collecte",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération collecte (FCFA)"
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="remuneration_collecte",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération collecte (FCFA)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
        migrations.AddField(
            model_name="relaypointpartner",
            name="remuneration_collecte",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération collecte (FCFA)"
            ),
        ),
        migrations.AddField(
            model_name="relaypointpartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
    ]
