# Generated by Django 5.0.7 on 2026-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0009_add_remuneration_livreur"),
    ]

    operations = [
        migrations.AddField(
            model_name="laundrypartner",
            name="level",
            field=models.CharField(
                choices=[
                    ("bronze", "🥉 Bronze"),
                    ("silver", "🥈 Silver"),
                    ("gold", "🥇 Gold"),
                ],
                default="bronze",
                max_length=10,
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="partner_score",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Score automatique sur 100 pts (délai 40 + litiges 30 + dispo 20 + refus 10)",
                verbose_name="Partner Score",
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("blanchisserie", "Blanchisserie"),
                    ("pressing", "Pressing premium"),
                ],
                default="blanchisserie",
                max_length=20,
                verbose_name="Type de partenaire",
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="score_delai",
            field=models.PositiveIntegerField(
                default=40, verbose_name="Score délai (sur 40)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="score_dispo",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Score disponibilité (sur 20)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="score_litiges",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Score litiges (sur 30)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="score_refus",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Score refus (sur 10)"
            ),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="score_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Score mis à jour le"
            ),
        ),
    ]
