# Generated by FAGNI
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_laundrypartner_level_laundrypartner_partner_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerScoreHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score",         models.PositiveIntegerField(verbose_name="Score total")),
                ("level",         models.CharField(max_length=10, verbose_name="Niveau")),
                ("score_delai",   models.PositiveIntegerField(default=0)),
                ("score_litiges", models.PositiveIntegerField(default=0)),
                ("score_dispo",   models.PositiveIntegerField(default=0)),
                ("score_refus",   models.PositiveIntegerField(default=0)),
                ("computed_at",   models.DateTimeField(auto_now_add=True, verbose_name="Calculé le")),
                ("partner", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="score_history",
                    to="partners.laundrypartner",
                )),
            ],
            options={
                "verbose_name": "Historique score partenaire",
                "verbose_name_plural": "Historiques scores partenaires",
                "ordering": ["-computed_at"],
            },
        ),
    ]
