# Generated by Django 5.0.7 on 2026-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0011_add_partner_score_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Le livreur est disponible pour recevoir des missions",
                verbose_name="En ligne",
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="went_online_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="En ligne depuis"
            ),
        ),
    ]
