# Generated by Django 5.0.7 on 2026-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0012_deliverypartner_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="cni_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Numéro CNI"
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="photo_cni_url",
            field=models.URLField(blank=True, default="", verbose_name="Photo CNI"),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="photo_profil_url",
            field=models.URLField(blank=True, default="", verbose_name="Photo profil"),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="photo_facade_url",
            field=models.URLField(blank=True, default="", verbose_name="Photo facade"),
        ),
        migrations.AddField(
            model_name="laundrypartner",
            name="rccm",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="RCCM"
            ),
        ),
    ]
