# Generated by Django 5.0.7 on 2026-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0013_deliverypartner_cni_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=800, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="laundrypartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=800, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="relaypointpartner",
            name="remuneration_livraison",
            field=models.PositiveIntegerField(
                default=800, verbose_name="Rémunération livraison (FCFA)"
            ),
        ),
    ]
