# Generated by Django 5.0.7 on 2026-03-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        ("orders", "0056_orderitem_service_type_alter_serviceitem_code"),
        ("partners", "0007_remove_deliverypartner_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_reception", "En attente de réception"),
                            ("received", "Reçu"),
                            ("weighed", "Pesé"),
                            ("confirmed", "Confirmé"),
                            ("processing", "En traitement"),
                            ("ready", "Prêt"),
                            ("handed_over", "Remis au livreur"),
                            ("issue", "Incident"),
                        ],
                        default="awaiting_reception",
                        max_length=30,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("handed_over_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_jobs_v2",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs_v2",
                        to="partners.laundrypartner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeighingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_by_role",
                    models.CharField(
                        choices=[
                            ("driver", "Livreur"),
                            ("partner", "Partenaire"),
                            ("ops", "Opérations"),
                            ("system", "Système"),
                        ],
                        default="driver",
                        max_length=20,
                    ),
                ),
                (
                    "weighing_stage",
                    models.CharField(
                        choices=[
                            ("pickup_estimate", "Estimation à la collecte"),
                            ("partner_reception", "Réception partenaire"),
                            ("final_validation", "Validation finale"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("net_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(default="kg", max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weighing_records",
                        to="logistics.mission",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weighing_records_v2",
                        to="orders.order",
                    ),
                ),
                (
                    "partner_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weighing_records",
                        to="production.partnerjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
