# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_add_paiement_model"),
        ("orders", "0071_add_paiement_model"),
        ("partners", "0008_add_wave_number"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerjob",
            options={
                "verbose_name": "Mission partenaire",
                "verbose_name_plural": "Missions partenaires",
            },
        ),
        migrations.AlterModelOptions(
            name="weighingrecord",
            options={"verbose_name": "Pesée", "verbose_name_plural": "Pesées"},
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="code",
            field=models.CharField(max_length=30, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_jobs_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs_v2",
                to="partners.laundrypartner",
                verbose_name="Partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_reception", "En attente de réception"),
                    ("received", "Reçu"),
                    ("weighed", "Pesé"),
                    ("confirmed", "Confirmé"),
                    ("processing", "En traitement"),
                    ("ready", "Prêt"),
                    ("handed_over", "Remis au livreur"),
                    ("issue", "Incident"),
                ],
                default="awaiting_reception",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighing_records",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weighing_records_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="partner_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighing_records",
                to="production.partnerjob",
                verbose_name="Mission partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="weighingrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
