# Generated by Django 5.0.7 on 2026-08-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_partnerjob_service_execution"),
        ("services", "0004_serviceexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="weighingrecord",
            name="service_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weighing_records",
                to="services.serviceexecution",
                verbose_name="Exécution de service",
            ),
        ),
    ]
