# Generated by Django 5.0.7 on 2026-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_weighingrecord_service_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerjob",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Annulé le"),
        ),
        migrations.AlterField(
            model_name="partnerjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_reception", "En attente de réception"),
                    ("received", "Reçu"),
                    ("weighed", "Pesé"),
                    ("confirmed", "Confirmé"),
                    ("processing", "En traitement"),
                    ("ready", "Prêt"),
                    ("handed_over", "Remis au livreur"),
                    ("issue", "Incident"),
                    ("canceled", "Annulé"),
                ],
                default="awaiting_reception",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
    ]
