# Generated by Django 5.0.7 on 2026-03-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_partner", models.BooleanField(default=True)),
                ("requires_logistics", models.BooleanField(default=True)),
                ("requires_weighing", models.BooleanField(default=False)),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            ("per_item", "Par article"),
                            ("per_kg", "Par kilo"),
                            ("fixed", "Forfait"),
                            ("quote_required", "Devis requis"),
                            ("hybrid", "Hybride"),
                        ],
                        default="per_item",
                        max_length=20,
                    ),
                ),
                ("default_sla_hours", models.PositiveIntegerField(default=48)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "extra_price_type",
                    models.CharField(
                        choices=[("fixed", "Montant fixe"), ("percent", "Pourcentage")],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "extra_price_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "code")},
            },
        ),
    ]
