# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "verbose_name": "Catégorie de service",
                "verbose_name_plural": "Catégories de service",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceoption",
            options={
                "verbose_name": "Option de service",
                "verbose_name_plural": "Options de service",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.servicecategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="service",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("per_item", "Par article"),
                    ("per_kg", "Par kilo"),
                    ("fixed", "Forfait"),
                    ("quote_required", "Devis requis"),
                    ("hybrid", "Hybride"),
                ],
                default="per_item",
                max_length=20,
                verbose_name="Mode de tarification",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="code",
            field=models.SlugField(verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
