# Generated by Django 5.0.7 on 2026-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_add_paiement_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="primary_engine",
            field=models.CharField(
                choices=[
                    ("pickup_return", "Collecte / traitement / retour"),
                    ("onsite", "Intervention sur site"),
                    ("appointment", "Rendez-vous"),
                ],
                db_index=True,
                default="pickup_return",
                max_length=30,
                verbose_name="Moteur principal",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_appointment",
            field=models.BooleanField(default=False, verbose_name="Rendez-vous requis"),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_asset",
            field=models.BooleanField(
                default=False,
                help_text="Exemple : véhicule pour une vidange. Le modèle de l'actif sera défini dans un lot dédié.",
                verbose_name="Actif / équipement client requis",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_otp",
            field=models.BooleanField(
                default=False, verbose_name="Validation OTP requise"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_quote",
            field=models.BooleanField(default=False, verbose_name="Devis requis"),
        ),
        migrations.AddField(
            model_name="service",
            name="requires_signature",
            field=models.BooleanField(default=False, verbose_name="Signature requise"),
        ),
        migrations.AlterField(
            model_name="service",
            name="default_sla_hours",
            field=models.PositiveIntegerField(
                default=48, verbose_name="SLA par défaut (heures)"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="requires_logistics",
            field=models.BooleanField(default=True, verbose_name="Logistique requise"),
        ),
        migrations.AlterField(
            model_name="service",
            name="requires_partner",
            field=models.BooleanField(default=True, verbose_name="Prestataire requis"),
        ),
        migrations.AlterField(
            model_name="service",
            name="requires_weighing",
            field=models.BooleanField(default=False, verbose_name="Pesée requise"),
        ),
    ]
