# Generated by Django 5.0.7 on 2026-08-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_alter_orderpaymentevent_channel"),
        (
            "services",
            "0003_service_primary_engine_service_requires_appointment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "execution_engine",
                    models.CharField(
                        choices=[
                            ("pickup_return", "Collecte / traitement / retour"),
                            ("onsite", "Intervention sur site"),
                            ("appointment", "Rendez-vous"),
                        ],
                        db_index=True,
                        help_text="Snapshot du moteur utilisé pour cette exécution. Ne doit pas dépendre dynamiquement de Service.primary_engine.",
                        max_length=30,
                        verbose_name="Moteur d'exécution",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("scheduled", "Planifiée"),
                            ("in_progress", "En cours"),
                            ("awaiting_validation", "En attente de validation"),
                            ("completed", "Terminée"),
                            ("canceled", "Annulée"),
                            ("failed", "Échouée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "sequence_index",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Permet à une commande de contenir plusieurs exécutions dans un ordre déterminé.",
                        verbose_name="Ordre d'exécution",
                    ),
                ),
                (
                    "planned_start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début planifié"
                    ),
                ),
                (
                    "planned_end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin planifiée"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début réel"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin réelle"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulée le"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données métier non structurelles et évolutives. Les données fréquemment filtrées ou critiques doivent devenir des colonnes ou modèles dédiés.",
                        verbose_name="Métadonnées métier",
                    ),
                ),
                (
                    "service_snapshot_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Capture optionnelle de la configuration du service au moment de la création de l'exécution.",
                        verbose_name="Snapshot du service",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_executions",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exécution de service",
                "verbose_name_plural": "Exécutions de services",
                "ordering": ("order_id", "sequence_index", "id"),
                "indexes": [
                    models.Index(
                        fields=["order", "status"], name="svc_exec_order_status_idx"
                    ),
                    models.Index(
                        fields=["service", "status"], name="svc_exec_service_status_idx"
                    ),
                    models.Index(
                        fields=["execution_engine", "status"],
                        name="svc_exec_engine_status_idx",
                    ),
                ],
            },
        ),
    ]
