# Generated by Django 5.0.7 on 2026-08-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_alter_orderpaymentevent_channel"),
        ("services", "0004_serviceexecution"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("vehicle", "Véhicule"),
                            ("equipment", "Équipement"),
                            ("machine", "Machine"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="Type d'actif",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom / désignation"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Exemple : immatriculation, numéro de série ou référence client.",
                        max_length=120,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données descriptives variables selon le type d'actif. Les informations critiques ou fréquemment filtrées devront devenir des champs dédiés.",
                        verbose_name="Métadonnées",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_assets",
                        to="orders.customer",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actif client",
                "verbose_name_plural": "Actifs clients",
                "ordering": ("customer_id", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="serviceexecution",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Actif concerné par cette exécution lorsque le service requiert un équipement client.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_executions",
                to="services.customerasset",
                verbose_name="Actif client",
            ),
        ),
        migrations.AddIndex(
            model_name="customerasset",
            index=models.Index(
                fields=["customer", "asset_type"], name="cust_asset_customer_type_idx"
            ),
        ),
    ]
