# Generated by Django 5.0.7 on 2026-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_customerasset_serviceexecution_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("per_item", "Par article"),
                    ("per_kg", "Par kilo"),
                    ("bag", "Par sac"),
                    ("fixed", "Forfait"),
                    ("quote_required", "Devis requis"),
                    ("hybrid", "Hybride"),
                ],
                default="per_item",
                max_length=20,
                verbose_name="Mode de tarification",
            ),
        ),
    ]
