# Generated by Django 5.0.7 on 2026-08-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_alter_orderpaymentevent_channel"),
        ("services", "0006_alter_service_pricing_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceExecutionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_execution_link",
                        to="orders.orderitem",
                        verbose_name="Ligne de commande",
                    ),
                ),
                (
                    "service_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_links",
                        to="services.serviceexecution",
                        verbose_name="Exécution de service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'exécution de service",
                "verbose_name_plural": "Lignes d'exécution de service",
                "ordering": ("service_execution_id", "order_item_id", "id"),
            },
        ),
    ]
