# Generated by Django 5.0.7 on 2026-08-15 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_alter_orderpaymentevent_channel"),
        ("services", "0007_serviceexecutionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceexecutionitem",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_execution_link",
                to="orders.orderitem",
                verbose_name="Ligne de commande",
            ),
        ),
    ]
