# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
            },
        ),
        migrations.AlterModelOptions(
            name="driverprofile",
            options={
                "verbose_name": "Profil livreur",
                "verbose_name_plural": "Profils livreurs",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "Rôle utilisateur",
                "verbose_name_plural": "Rôles utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Vérifié"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Note"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
