# Generated by Django 5.0.7 on 2025-11-26 12:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0017_remove_customer_email_alter_customer_name_and_more'),
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('customer', 'Client FAGNI'), ('laundry', 'Blanchisserie partenaire'), ('driver', 'Livreur partenaire'), ('internal', 'Interne FAGNI')], max_length=20, verbose_name='Type de propriétaire')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='orders.customer', verbose_name='Client')),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='partners.deliverypartner', verbose_name='Livreur partenaire')),
                ('laundry_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='partners.laundrypartner', verbose_name='Blanchisserie partenaire')),
                ('relay_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='partners.relaypointpartner', verbose_name='Point relais partenaire')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur (interne)')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Recharge / Dépôt'), ('payout', 'Paiement sortant'), ('mlm_commission', 'Commission MLM'), ('adjustment', 'Ajustement manuel'), ('credit', 'Crédit'), ('debit', 'Débit')], max_length=30, verbose_name='Type de transaction')),
                ('direction', models.CharField(choices=[('in', 'Entrant'), ('out', 'Sortant')], max_length=5, verbose_name='Sens')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_wallets', to='orders.order', verbose_name='Commande liée')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction de wallet',
                'verbose_name_plural': 'Transactions de wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
