# Generated by Django 5.0.7 on 2025-12-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('approved', 'Approuvée (en cours de paiement)'), ('rejected', 'Rejetée'), ('paid', 'Payée au bénéficiaire')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé / traité le')),
                ('notes', models.TextField(blank=True, help_text='Commentaires internes sur la demande (motif, référence de paiement réelle, etc.).', verbose_name='Notes internes')),
                ('external_reference', models.CharField(blank=True, help_text='Référence de la transaction réelle auprès du PSP ou de la banque.', max_length=120, verbose_name='Référence externe (OM / MTN / banque…)')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Souvent lié à un compte livreur ou blanchisserie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur demandeur')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
