# Generated by Django 5.0.7 on 2025-12-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
        ('wallets', '0002_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Note admin'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='partners.deliverypartner', verbose_name='Livreur partenaire'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traitée le'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur demandeur'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
