# Generated by Django 5.0.7 on 2025-12-08 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
        ('wallets', '0003_remove_withdrawalrequest_external_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de retrait livreur', 'verbose_name_plural': 'Demandes de retrait livreur'},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='admin_note',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='delivery_partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partners.deliverypartner', verbose_name='Livreur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_requested', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par (user)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet', verbose_name='Wallet livreur'),
        ),
    ]
