# Generated by Django 5.0.7 on 2025-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_driver_wallet_credited'),
        ('wallets', '0010_alter_wallet_owner_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('wallet', 'order', 'type', 'direction'), name='uniq_wtx_wallet_order_type_dir'),
        ),
    ]
