# Generated by Django 5.0.7 on 2025-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_withdrawalrequest_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('wallet', 'order', 'type', 'direction'), name='uniq_wtx_wallet_order_type_dir'),
        ),
    ]
