# Generated by Django 5.0.7 on 2025-12-19 12:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_driver_wallet_credited_payment'),
        ('partners', '0005_seed_demo_partners'),
        ('wallets', '0011_wallettransaction_uniq_wtx_wallet_order_type_dir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction wallet', 'verbose_name_plural': 'Transactions wallet'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner_type',
            field=models.CharField(choices=[('customer', 'Client FAGNI'), ('laundry', 'Blanchisserie partenaire'), ('driver', 'Livreur partenaire'), ('relay', 'Point relais partenaire'), ('internal', 'Interne FAGNI')], max_length=20, verbose_name='Type de propriétaire'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='direction',
            field=models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10, verbose_name='Sens'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit'), ('payout', 'Paiement / Retrait'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement')], max_length=30, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'customer'), ('customer__isnull', False)), fields=('customer', 'currency'), name='uniq_wallet_customer_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'laundry'), ('laundry_partner__isnull', False)), fields=('laundry_partner', 'currency'), name='uniq_wallet_laundry_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'relay'), ('relay_partner__isnull', False)), fields=('relay_partner', 'currency'), name='uniq_wallet_relay_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'driver'), ('delivery_partner__isnull', False)), fields=('delivery_partner', 'currency'), name='uniq_wallet_driver_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'internal'), ('user__isnull', False)), fields=('user', 'currency'), name='uniq_wallet_internal_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'internal'), ('user__isnull', True)), fields=('currency',), name='uniq_wallet_internal_platform_currency'),
        ),
    ]
