# Generated by Django 5.0.7 on 2025-12-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_driver_wallet_credited_payment'),
        ('wallets', '0012_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='uniq_wtx_wallet_order_type_dir',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.deliveryleg', verbose_name='Tronçon (leg)'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('leg__isnull', False)), fields=('wallet', 'leg', 'type', 'direction'), name='uniq_wtx_wallet_leg_type_dir'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('leg__isnull', True)), fields=('wallet', 'order', 'type', 'direction'), name='uniq_wtx_wallet_order_type_dir'),
        ),
    ]
