# Generated by Django 5.0.7 on 2025-12-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_order_driver_wallet_credited_payment'),
        ('wallets', '0013_remove_wallettransaction_uniq_wtx_wallet_order_type_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='orders.deliveryleg', verbose_name='Tronçon (leg)'),
        ),
    ]
