# Generated by Django 5.0.7 on 2026-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_deliveryleg_driver'),
        ('wallets', '0014_alter_wallettransaction_leg'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('leg__isnull', False)), fields=('order', 'leg', 'type', 'direction'), name='uniq_wtx_order_leg_type_dir'),
        ),
    ]
