# Generated by Django 5.0.7 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0015_wallettransaction_uniq_wtx_order_leg_type_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit'), ('payout', 'Paiement / Retrait'), ('refund', 'Remboursement'), ('adjustment', 'Ajustement'), ('legacy_payout', 'Legacy payout')], max_length=30, verbose_name='Type'),
        ),
    ]
