# Generated by Django 5.0.7 on 2026-02-02 18:53

from django.db import migrations, models


def _drop_legacy_constraint_or_index(apps, schema_editor, name: str):
    """
    Tolérant:
    - SQLite: les UniqueConstraint historiques sont matérialisées en INDEX => DROP INDEX IF EXISTS
    - Postgres: ALTER TABLE ... DROP CONSTRAINT IF EXISTS
    - Fallback: tenter aussi DROP INDEX IF EXISTS
    """
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()

    if vendor == "sqlite":
        cursor.execute(f'DROP INDEX IF EXISTS "{name}"')
        return

    if vendor == "postgresql":
        # Contrainte (le plus probable)
        try:
            cursor.execute(f'ALTER TABLE "wallets_wallettransaction" DROP CONSTRAINT IF EXISTS "{name}"')
        except Exception:
            pass
        # Parfois c’est un index
        try:
            cursor.execute(f'DROP INDEX IF EXISTS "{name}"')
        except Exception:
            pass
        return

    # MySQL / autres: tenter index + ignorer si ça casse
    try:
        cursor.execute(f'DROP INDEX "{name}" ON "wallets_wallettransaction"')
    except Exception:
        pass
    try:
        cursor.execute(f'DROP INDEX IF EXISTS "{name}"')
    except Exception:
        pass


def drop_legacy_uniqs(apps, schema_editor):
    for n in ("uniq_wtx_wallet_leg_type_dir", "uniq_wtx_wallet_order_type_dir", "uniq_wtx_order_leg_type_dir"):
        _drop_legacy_constraint_or_index(apps, schema_editor, n)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0044_add_wallettransaction_idempotency_key"),
        ("wallets", "0016_alter_wallettransaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallettransaction",
            options={},
        ),

        # ✅ DB ops tolérantes, mais on retire quand même l'état Django (state_operations)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_uniqs, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="wallettransaction",
                    name="uniq_wtx_wallet_leg_type_dir",
                ),
                migrations.RemoveConstraint(
                    model_name="wallettransaction",
                    name="uniq_wtx_wallet_order_type_dir",
                ),
                migrations.RemoveConstraint(
                    model_name="wallettransaction",
                    name="uniq_wtx_order_leg_type_dir",
                ),
            ],
        ),

        migrations.AddField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=120,
                null=True,
                verbose_name="Clé idempotence",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="uniq_wallettx_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("leg__isnull", True)),
                fields=("wallet", "order", "type", "direction"),
                name="uniq_wallet_order_type_dir_no_leg",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("leg__isnull", False)),
                fields=("wallet", "order", "type", "direction", "leg"),
                name="uniq_wallet_order_type_dir_leg",
            ),
        ),
    ]
