# Generated by Django 5.0.7 on 2026-02-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0017_add_wallettransaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de retrait', 'verbose_name_plural': 'Demandes de retrait'},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='delivery_partner',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet', verbose_name='Wallet'),
        ),
    ]
