# Generated by ChatGPT on 2026-02-10
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0018_alter_withdrawalrequest_options_and_more"),
    ]

    operations = [
        # ✅ 1 seul payout IN par (order, leg) — peu importe le wallet
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                fields=("order", "leg", "type", "direction"),
                condition=Q(order__isnull=False) & Q(leg__isnull=False) & Q(type="payout") & Q(direction="in"),
                name="uniq_payout_in_per_order_leg",
            ),
        ),
    ]
