# Generated by Django 5.0.7 on 2026-02-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0019_uniq_payout_per_leg'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='uniq_payout_in_per_order_leg',
        ),
    ]
