# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_add_paiement_model"),
        ("wallets", "0020_remove_wallettransaction_uniq_payout_in_per_order_leg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="orders.customer",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="wallets.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to="wallets.wallet",
            ),
        ),
    ]
