# Generated by Django 5.0.7 on 2026-09-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd", "0001_initial_crowd_models"),
        ("wallets", "0022_wallet_balance_securite"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="cotransporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="crowd.cotransporter",
                verbose_name="Cotransporteur Crowd",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("customer", "Client FAGNI"),
                    ("laundry", "Blanchisserie partenaire"),
                    ("driver", "Livreur partenaire"),
                    ("relay", "Point relais partenaire"),
                    ("internal", "Interne FAGNI"),
                    ("cotransporter", "Cotransporteur Crowd"),
                ],
                max_length=20,
                verbose_name="Type de propriétaire",
            ),
        ),
    ]
