# Generated by Django 5.0.7 on 2025-11-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_delivery_partner_order_laundry_partner'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('customer', 'Client'), ('laundry', 'Blanchisserie'), ('delivery', 'Livreur')], max_length=20, verbose_name="Type d'acteur")),
                ('referral_code', models.CharField(help_text="Code que cet acteur partage pour parrainer d'autres acteurs.", max_length=20, unique=True, verbose_name='Code de parrainage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='orders.customer')),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='partners.deliverypartner')),
                ('laundry_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='partners.laundrypartner')),
                ('sponsor', models.ForeignKey(blank=True, help_text='Profil MLM qui a directement parrainé cet acteur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to='mlm.referrallink')),
            ],
            options={
                'verbose_name': 'Profil MLM',
                'verbose_name_plural': 'Profils MLM',
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3')], verbose_name='Niveau')),
                ('service_fee_base', models.PositiveIntegerField(help_text='Service fee FAGNI (en FCFA) utilisé comme base pour la commission (5% min 500F).', verbose_name='Base service_fee (FCFA)')),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='5.00 pour 5%, 3.00 pour 3%, 1.00 pour 1%, etc.', max_digits=5, verbose_name='Pourcentage appliqué')),
                ('commission_amount', models.PositiveIntegerField(verbose_name='Montant commission (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payée ?')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='orders.order', verbose_name='Commande')),
                ('beneficiary_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mlm.referrallink', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Commission MLM',
                'verbose_name_plural': 'Commissions MLM',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mlm_commission', 'Commission MLM'), ('payout', 'Retrait / paiement'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type')),
                ('amount', models.IntegerField(help_text='Montant en FCFA (positif = crédit, négatif = débit).', verbose_name='Montant (FCFA)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='Commande liée')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='mlm.referrallink', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Transaction de wallet',
                'verbose_name_plural': 'Transactions de wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
