# Generated by Django 5.0.7 on 2025-11-16 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
        ('orders', '0004_order_delivery_partner_order_laundry_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction Wallet', 'verbose_name_plural': 'Transactions Wallet'},
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='beneficiary_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mlm.referrallink'),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='commission_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3')]),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='service_fee_base',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code de parrainage'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='Profil MLM qui a directement parrainé cet acteur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to='mlm.referrallink'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='mlm.referrallink'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('mlm_commission', 'Commission MLM'), ('payout', 'Retrait / paiement'), ('adjustment', 'Ajustement')], max_length=20),
        ),
    ]
