# Generated by Django 5.0.7 on 2025-11-22 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_alter_wallettransaction_options_and_more'),
        ('orders', '0016_order_relay_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='orders.customer')),
            ],
            options={
                'verbose_name': 'Wallet client',
                'verbose_name_plural': 'Wallets clients',
            },
        ),
        migrations.CreateModel(
            name='CustomerWalletMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Crédit simple'), ('debit', 'Débit simple'), ('order_payment', 'Paiement commande'), ('refund', 'Remboursement commande'), ('cashback', 'Cashback'), ('mlm_commission', 'Commission MLM'), ('bonus', 'Bonus fidélité'), ('microcredit', 'Décaissement micro-crédit'), ('microcredit_repay', 'Remboursement micro-crédit'), ('manual_adjustment', 'Ajustement manuel')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_moves_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_moves', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='mlm.customerwallet')),
            ],
            options={
                'verbose_name': 'Mouvement wallet client',
                'verbose_name_plural': 'Mouvements wallet client',
                'ordering': ['-created_at'],
            },
        ),
    ]
