# Generated by Django 5.0.7 on 2025-11-22 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_customerwallet_customerwalletmove'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan standard 3 niveaux', max_length=100)),
                ('level1_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('level2_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('level3_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration MLM',
                'verbose_name_plural': 'Configurations MLM',
            },
        ),
    ]
