# Generated by Django 5.0.7 on 2025-11-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_mlmconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant demandé en FCFA')),
                ('payout_method', models.CharField(help_text='Mode de paiement souhaité (Mobile Money, virement, espèces, etc.)', max_length=100)),
                ('note', models.CharField(blank=True, help_text="Commentaire de l'affilié ou du back-office", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='mlm.wallettransaction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='mlm.referrallink')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
    ]
