# Generated by Django 5.0.7 on 2025-11-23 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0005_withdrawalrequest'),
        ('orders', '0016_order_relay_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerwallet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerwalletmove',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='customerwalletmove',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerwalletmove',
            name='order',
        ),
        migrations.DeleteModel(
            name='MLMConfig',
        ),
        migrations.RemoveField(
            model_name='referralcommission',
            name='beneficiary_profile',
        ),
        migrations.RemoveField(
            model_name='referralcommission',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='referrallink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='delivery_partner',
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='laundry_partner',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='note',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payout_method',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payout_transaction',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(blank=True, help_text='Moyen de paiement (Mobile Money, virement, cash, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes (admin) ou commentaire sur la demande.'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='actor_type',
            field=models.CharField(choices=[('customer', 'Client'), ('driver', 'Livreur'), ('laundry', 'Blanchisserie'), ('relay', 'Point relais'), ('other', 'Autre')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='orders.customer'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to='mlm.referrallink'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('mlm_commission', 'Commission MLM'), ('payout', 'Retrait / Paiement'), ('adjustment', 'Ajustement manuel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='mlm.referrallink'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mlmcommission',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mlm.referrallink'),
        ),
        migrations.AddField(
            model_name='mlmcommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='CustomerWallet',
        ),
        migrations.DeleteModel(
            name='CustomerWalletMove',
        ),
        migrations.DeleteModel(
            name='ReferralCommission',
        ),
        migrations.AlterUniqueTogether(
            name='mlmcommission',
            unique_together={('affiliate', 'order', 'level')},
        ),
    ]
