# Generated by Django 5.0.7 on 2025-11-23 02:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_mlmcommission_remove_customerwallet_customer_and_more'),
        ('orders', '0017_remove_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrallink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil de parrainage', 'verbose_name_plural': 'Profils de parrainage'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction Wallet', 'verbose_name_plural': 'Transactions Wallet'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Demande de retrait', 'verbose_name_plural': 'Demandes de retrait'},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='method',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de demande'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='actor_type',
            field=models.CharField(choices=[('client', 'Client particulier'), ('influencer', "Influenceur / apporteur d'affaires"), ('corporate', 'Entreprise / partenaire')], default='client', max_length=20, verbose_name="Type d'acteur"),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_profiles', to='orders.customer', verbose_name='Client FAGNI'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code affilié'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to='mlm.referrallink', verbose_name='Parrain'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.IntegerField(help_text='Positif pour crédit, négatif pour débit.', verbose_name='Montant (FCFA)'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='Commande liée'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='mlm.referrallink', verbose_name='Profil de parrainage'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('mlm_commission', 'Commission MLM'), ('payout', 'Retrait / paiement'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant demandé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traitée le'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='mlm.referrallink', verbose_name='Profil affilié'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='1 = filleul direct, 2 = 2e niveau, 3 = 3e niveau', verbose_name='Niveau')),
                ('service_fee_base', models.IntegerField(help_text='Montant du service FAGNI utilisé comme base de calcul.', verbose_name='Base service fee (FCFA)')),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='Ex : 5.00 pour 5 %', max_digits=5, verbose_name='Pourcentage appliqué')),
                ('commission_amount', models.IntegerField(verbose_name='Montant de la commission (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('beneficiary_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mlm.referrallink', verbose_name='Bénéficiaire')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Commission MLM',
                'verbose_name_plural': 'Commissions MLM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MLMCommission',
        ),
    ]
