# Generated by Django 5.0.7 on 2025-11-23 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0007_alter_referrallink_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de retrait', 'verbose_name_plural': 'Demandes de retrait'},
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créée le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(blank=True, help_text='Ex : Mobile Money, virement, espèce…', max_length=50, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Référence de transaction / reçu…', max_length=100, verbose_name='Référence de paiement'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
    ]
