# Generated by Django 5.0.7 on 2025-11-23 11:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0008_alter_withdrawalrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuration MLM par défaut', help_text="Permet d'identifier ce set de paramètres dans l'admin.", max_length=100, verbose_name='Nom du profil de configuration')),
                ('enabled', models.BooleanField(default=True, help_text="Si désactivé, aucune nouvelle commission n'est générée.", verbose_name='MLM activé')),
                ('allow_withdrawals', models.BooleanField(default=True, help_text='Si désactivé, les affiliés ne peuvent pas soumettre de nouvelles demandes de retrait.', verbose_name='Autoriser les retraits')),
                ('level1_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage du service FAGNI versé au parrain direct (N1).', max_digits=5, verbose_name='Pourcentage niveau 1 (N1)')),
                ('level2_percent', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pourcentage du service FAGNI versé au niveau 2 (N2).', max_digits=5, verbose_name='Pourcentage niveau 2 (N2)')),
                ('level3_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Pourcentage du service FAGNI versé au niveau 3 (N3).', max_digits=5, verbose_name='Pourcentage niveau 3 (N3)')),
                ('min_withdraw_amount', models.PositiveIntegerField(default=5000, help_text="Solde minimum que l'affilié doit atteindre pour demander un retrait.", verbose_name='Montant minimum de retrait (FCFA)')),
                ('min_service_fee_for_commission', models.PositiveIntegerField(default=500, help_text="En dessous de ce montant de service FAGNI, aucune commission n'est générée.", verbose_name='Service fee minimum pour générer des commissions (FCFA)')),
                ('max_daily_commission_per_profile', models.PositiveIntegerField(default=0, help_text='0 = pas de plafond. Sinon, limite le total de commissions MLM créditées sur un profil par jour.', verbose_name='Plafond quotidien par affilié (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Paramètres MLM',
                'verbose_name_plural': 'Paramètres MLM',
            },
        ),
    ]
