# Generated by Django 5.0.7 on 2025-11-23 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0009_mlmsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paramètres MLM', 'verbose_name_plural': 'Paramètres MLM'},
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='allow_withdrawals',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='max_daily_commission_per_profile',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='min_withdraw_amount',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='allow_negative_wallet',
            field=models.BooleanField(default=False, help_text='Si coché, certains ajustements pourront faire passer le wallet en négatif.', verbose_name='Autoriser les soldes négatifs'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='max_payout_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Plafond par retrait. Laisser vide pour aucun plafond.', null=True, verbose_name='Montant maximum de retrait (FCFA)'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='min_payout_amount',
            field=models.PositiveIntegerField(default=2000, help_text="Montant minimum qu'un affilié doit atteindre pour demander un retrait.", verbose_name='Montant minimum de retrait (FCFA)'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Si désactivé, aucune nouvelle commission MLM ne sera générée.', verbose_name='MLM actif'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level1_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage pour le niveau 1 (filleul direct). Ex : 10.00 pour 10 %.', max_digits=5, verbose_name='Pourcentage N1'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level2_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pourcentage pour le niveau 2. Ex : 3.00 pour 3 %.', max_digits=5, verbose_name='Pourcentage N2'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level3_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Pourcentage pour le niveau 3. Ex : 2.00 pour 2 %.', max_digits=5, verbose_name='Pourcentage N3'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='min_service_fee_for_commission',
            field=models.PositiveIntegerField(default=500, help_text="En dessous de ce montant de service FAGNI, aucune commission MLM n'est générée.", verbose_name='Service fee minimum pour générer des commissions (FCFA)'),
        ),
    ]
