# Generated by Django 5.0.7 on 2025-11-23 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0010_alter_mlmsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmsettings',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='max_payout_amount',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='min_payout_amount',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='min_service_fee_for_commission',
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Un seul profil actif devrait être utilisé en production.', verbose_name='Profil actif'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='max_daily_withdrawal',
            field=models.PositiveIntegerField(default=200000, verbose_name='Plafond quotidien de retrait (FCFA)'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='min_withdrawal_amount',
            field=models.PositiveIntegerField(default=5000, verbose_name='Montant minimal de retrait (FCFA)'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='name',
            field=models.CharField(default='Paramètres MLM 15% (10/3/2)', max_length=100, verbose_name='Nom du profil'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='allow_negative_wallet',
            field=models.BooleanField(default=False, help_text='À laisser sur Non en production.', verbose_name='Autoriser un solde wallet négatif'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level1_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage du service_fee redistribué au niveau 1.', max_digits=5, verbose_name='Pourcentage N1'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level2_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pourcentage du service_fee redistribué au niveau 2.', max_digits=5, verbose_name='Pourcentage N2'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='level3_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Pourcentage du service_fee redistribué au niveau 3.', max_digits=5, verbose_name='Pourcentage N3'),
        ),
    ]
