# Generated by Django 5.0.7 on 2025-11-23 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0011_remove_mlmsettings_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paramétrage MLM', 'verbose_name_plural': 'Paramétrages MLM'},
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='level1_percent',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='level2_percent',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='level3_percent',
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='max_daily_withdrawal',
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Une seule configuration active doit exister en production.', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='n1_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage niveau 1 (parrain direct), ex : 10.00 pour 10 %.', max_digits=5, verbose_name='Pourcentage N1'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='n2_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Pourcentage niveau 2, ex : 3.00 pour 3 %.', max_digits=5, verbose_name='Pourcentage N2'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='n3_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Pourcentage niveau 3, ex : 2.00 pour 2 %.', max_digits=5, verbose_name='Pourcentage N3'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='total_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Doit correspondrre à la somme N1+N2+N3 (ici 15 %).', max_digits=5, verbose_name='Pourcentage total distribué'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='allow_negative_wallet',
            field=models.BooleanField(default=False, verbose_name='Autoriser un solde wallet négatif'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='min_withdrawal_amount',
            field=models.PositiveIntegerField(default=5000, verbose_name='Montant minimum de retrait (FCFA)'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='name',
            field=models.CharField(default='Configuration par défaut', max_length=100, verbose_name='Nom de la configuration'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
    ]
