# Generated by Django 5.0.7 on 2025-11-23 13:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0012_alter_mlmsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmsettings',
            options={'verbose_name': 'Paramétrage MLM', 'verbose_name_plural': 'Paramétrages MLM'},
        ),
        migrations.RemoveField(
            model_name='mlmsettings',
            name='enabled',
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='max_daily_withdrawal',
            field=models.PositiveIntegerField(default=200000, verbose_name='Plafond de retrait par jour (FCFA)'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='min_service_fee_for_commission',
            field=models.PositiveIntegerField(default=500, help_text="En-dessous de ce montant de service FAGNI, aucune commission MLM n'est générée.", verbose_name='Service fee minimum pour commissions (FCFA)'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='allow_negative_wallet',
            field=models.BooleanField(default=False, verbose_name='Autoriser un wallet négatif ?'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='n1_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Commission niveau 1 (en % du service FAGNI).', max_digits=5, verbose_name='Pourcentage N1'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='n2_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Commission niveau 2 (en % du service FAGNI).', max_digits=5, verbose_name='Pourcentage N2'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='n3_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Commission niveau 3 (en % du service FAGNI).', max_digits=5, verbose_name='Pourcentage N3'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='name',
            field=models.CharField(default='Paramétrage par défaut', max_length=100, verbose_name='Nom du paramétrage'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='total_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='N1 + N2 + N3 (pour info / cohérence).', max_digits=5, verbose_name='Pourcentage total théorique'),
        ),
        migrations.AlterField(
            model_name='mlmsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
