# Generated by Django 5.0.7 on 2025-12-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0013_alter_mlmsettings_options_remove_mlmsettings_enabled_and_more'),
        ('orders', '0038_order_driver_wallet_credited_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlm_wallet_transactions', to='orders.order'),
        ),
    ]
