# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlm", "0014_alter_wallettransaction_order"),
        ("orders", "0071_add_paiement_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmsettings",
            name="min_withdrawal_amount",
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name="referralcommission",
            name="beneficiary_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="mlm.referrallink",
            ),
        ),
        migrations.AlterField(
            model_name="referralcommission",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mlm_commissions",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_profiles",
                to="orders.customer",
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_referrals",
                to="mlm.referrallink",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_transactions",
                to="mlm.referrallink",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
