# Generated by Django 5.0.7 on 2025-11-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('orders_count', models.IntegerField(default=0)),
                ('done_count', models.IntegerField(default=0)),
                ('success_rate', models.IntegerField(default=0)),
                ('peak_rides', models.IntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_eta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_bonuses', to='partners.deliverypartner')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('driver', 'week_start')},
            },
        ),
    ]
