# Generated by Django 5.0.7 on 2025-11-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
    ]

    operations = [
    ]
