# Generated by Django 5.0.7 on 2026-03-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        ("orders", "0056_orderitem_service_type_alter_serviceitem_code"),
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("customer_absent", "Client absent"),
                            ("partner_closed", "Partenaire fermé"),
                            ("missing_item", "Article manquant"),
                            ("wrong_weight", "Poids incorrect"),
                            ("damaged_item", "Article endommagé"),
                            ("payment_issue", "Problème de paiement"),
                            ("address_issue", "Problème d'adresse"),
                            ("delay", "Retard"),
                            ("delivery_failed", "Livraison échouée"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_review", "En revue"),
                            ("resolved", "Résolu"),
                            ("closed", "Clôturé"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("resolution_notes", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="logistics.mission",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents_v2",
                        to="orders.order",
                    ),
                ),
                (
                    "partner_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="production.partnerjob",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("signature", "Signature"),
                            ("otp", "OTP"),
                            ("qr_scan", "QR Scan"),
                            ("barcode_scan", "Code-barres"),
                            ("receipt", "Reçu"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="proofs/")),
                ("text_value", models.CharField(blank=True, max_length=255)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_proofs_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proofs",
                        to="logistics.mission",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs_v2",
                        to="orders.order",
                    ),
                ),
                (
                    "partner_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proofs",
                        to="production.partnerjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Commande créée"),
                            ("mission_assigned", "Mission assignée"),
                            ("mission_started", "Mission démarrée"),
                            ("pickup_confirmed", "Collecte confirmée"),
                            ("partner_received", "Réception partenaire"),
                            ("weighing_recorded", "Pesée enregistrée"),
                            ("production_started", "Production démarrée"),
                            ("production_ready", "Production prête"),
                            ("delivery_completed", "Livraison terminée"),
                            ("payment_confirmed", "Paiement confirmé"),
                            ("issue_reported", "Incident signalé"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("driver", "Livreur"),
                            ("partner", "Partenaire"),
                            ("ops", "Opérations"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("status_before", models.CharField(blank=True, max_length=50)),
                ("status_after", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="logistics.mission",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events_v2",
                        to="orders.order",
                    ),
                ),
                (
                    "partner_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="production.partnerjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
