# Generated by Django 5.0.7 on 2026-05-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_add_paiement_model"),
        ("orders", "0071_add_paiement_model"),
        ("production", "0002_add_paiement_model"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"verbose_name": "Incident", "verbose_name_plural": "Incidents"},
        ),
        migrations.AlterModelOptions(
            name="proof",
            options={"verbose_name": "Preuve", "verbose_name_plural": "Preuves"},
        ),
        migrations.AlterModelOptions(
            name="trackingevent",
            options={
                "verbose_name": "Événement de suivi",
                "verbose_name_plural": "Événements de suivi",
            },
        ),
        migrations.AlterField(
            model_name="incident",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_incidents_v2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigné à",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("customer_absent", "Client absent"),
                    ("partner_closed", "Partenaire fermé"),
                    ("missing_item", "Article manquant"),
                    ("wrong_weight", "Poids incorrect"),
                    ("damaged_item", "Article endommagé"),
                    ("payment_issue", "Problème de paiement"),
                    ("address_issue", "Problème d'adresse"),
                    ("delay", "Retard"),
                    ("delivery_failed", "Livraison échouée"),
                ],
                max_length=30,
                verbose_name="Type d'incident",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="partner_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="production.partnerjob",
                verbose_name="Mission partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="reported_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Signalé le"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_incidents_v2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Signalé par",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="resolution_notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Résolu le"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Faible"),
                    ("medium", "Moyenne"),
                    ("high", "Haute"),
                    ("critical", "Critique"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Sévérité",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Ouvert"),
                    ("in_review", "En revue"),
                    ("resolved", "Résolu"),
                    ("closed", "Clôturé"),
                ],
                default="open",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="proof",
            name="captured_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Capturé le"),
        ),
        migrations.AlterField(
            model_name="proof",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captured_proofs_v2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Capturé par",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="proof",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="proofs/", verbose_name="Fichier"
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proofs",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="proof",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="partner_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proofs",
                to="production.partnerjob",
                verbose_name="Mission partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="proof_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo"),
                    ("signature", "Signature"),
                    ("otp", "OTP"),
                    ("qr_scan", "QR Scan"),
                    ("barcode_scan", "Code-barres"),
                    ("receipt", "Reçu"),
                ],
                max_length=30,
                verbose_name="Type de preuve",
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="text_value",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Valeur texte"
            ),
        ),
        migrations.AlterField(
            model_name="proof",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="actor_role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("driver", "Livreur"),
                    ("partner", "Partenaire"),
                    ("ops", "Opérations"),
                    ("system", "Système"),
                ],
                default="system",
                max_length=20,
                verbose_name="Rôle acteur",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking_events_v2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur acteur",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Commande créée"),
                    ("mission_assigned", "Mission assignée"),
                    ("mission_started", "Mission démarrée"),
                    ("pickup_confirmed", "Collecte confirmée"),
                    ("partner_received", "Réception partenaire"),
                    ("weighing_recorded", "Pesée enregistrée"),
                    ("production_started", "Production démarrée"),
                    ("production_ready", "Production prête"),
                    ("delivery_completed", "Livraison terminée"),
                    ("payment_confirmed", "Paiement confirmé"),
                    ("issue_reported", "Incident signalé"),
                ],
                max_length=30,
                verbose_name="Type d'événement",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="metadata_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Métadonnées"
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking_events",
                to="logistics.mission",
                verbose_name="Mission",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events_v2",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="partner_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking_events",
                to="production.partnerjob",
                verbose_name="Mission partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="status_after",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Statut après"
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="status_before",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Statut avant"
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
