# Generated by Django 5.0.7 on 2026-08-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_serviceexecution"),
        ("tracking", "0002_add_paiement_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="service_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="services.serviceexecution",
                verbose_name="Exécution de service",
            ),
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="service_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracking_events",
                to="services.serviceexecution",
                verbose_name="Exécution de service",
            ),
        ),
    ]
