# Generated by Django 5.0.7 on 2025-10-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_total_orderitem_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
