# Generated by Django 5.0.7 on 2025-11-16 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_payment_order_delete_delivery_delete_payment'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='partners.deliverypartner', verbose_name='Livreur partenaire'),
        ),
        migrations.AddField(
            model_name='order',
            name='laundry_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='partners.laundrypartner', verbose_name='Blanchisserie partenaire'),
        ),
    ]
