# Generated by Django 5.0.7 on 2025-11-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_partner_order_laundry_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service FAGNI (FCFA)'),
        ),
    ]
