# Generated by Django 5.0.7 on 2025-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Livrée au client'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Déposée à la blanchisserie'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Collectée par le livreur'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reprise par le livreur'),
        ),
        migrations.AddField(
            model_name='order',
            name='wash_complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de lavage'),
        ),
    ]
