# Generated by Django 5.0.7 on 2025-11-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_logistic_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Coût livreur estimé'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistic_margin',
            field=models.IntegerField(default=0, verbose_name='Marge logistique FAGNI'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Frais de livraison (client)'),
        ),
    ]
