# Generated by Django 5.0.7 on 2025-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_driver_logistic_cost_order_logistic_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison (client)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_logistic_cost',
            field=models.IntegerField(default=0),
        ),
    ]
