# Generated by Django 5.0.7 on 2025-11-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance totale (km)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison (FCFA)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_logistic_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût logistique livreur (FCFA)'),
        ),
    ]
