# Generated by Django 5.0.7 on 2025-11-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_distance_km_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_items/photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.orderitem', verbose_name='Ligne de commande')),
            ],
            options={
                'verbose_name': "Photo d'article",
                'verbose_name_plural': "Photos d'articles",
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code interne')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.servicecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Prestation / Article',
                'verbose_name_plural': 'Prestations / Articles',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.serviceitem', verbose_name='Prestation cataloguée'),
        ),
    ]
