# Generated by Django 5.0.7 on 2025-11-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_servicecategory_orderitemphoto_serviceitem_and_more'),
        ('partners', '0003_relaypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relay_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='partners.relaypoint', verbose_name='Point relais partenaire'),
        ),
    ]
