# Generated by Django 5.0.7 on 2025-11-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_relay_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='relay_point',
        ),
    ]
