# Generated by Django 5.0.7 on 2025-11-20 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_relay_point'),
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relay_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='partners.relaypointpartner', verbose_name='Point relais partenaire'),
        ),
    ]
