# Generated by Django 5.0.7 on 2025-11-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_customer_email_alter_customer_name_and_more'),
        ('partners', '0004_relaypointpartner_delete_relaypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_type', models.CharField(choices=[('pickup', 'Client → Blanchisserie'), ('return', 'Blanchisserie → Client')], max_length=20, verbose_name='Type de jambe')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assignée'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('canceled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance (km)')),
                ('client_fee_share', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part client (FCFA)')),
                ('driver_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant livreur (FCFA)')),
                ('fagni_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Marge FAGNI (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début de la course')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la course')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_legs', to='partners.deliverypartner', verbose_name='Livreur partenaire')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Jambe de livraison',
                'verbose_name_plural': 'Jambes de livraison',
                'ordering': ['-created_at'],
            },
        ),
    ]
