# Generated by Django 5.0.7 on 2025-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_deliveryleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes sur la commande (consignes, contexte, etc.)', null=True, verbose_name='Notes / instructions internes'),
        ),
    ]
