# Generated by Django 5.0.7 on 2025-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderstatushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_pickup_at',
            field=models.DateTimeField(blank=True, help_text='Si renseigné, la collecte est prévue à cette date/heure.', null=True, verbose_name='Date/heure de collecte programmée'),
        ),
    ]
