# Generated by Django 5.0.7 on 2025-12-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_options_order_scheduled_pickup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Code parrain saisi lors de la création de la commande.', max_length=50, null=True, verbose_name='Code parrain saisi'),
        ),
    ]
