# Generated by Django 5.0.7 on 2025-12-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='order',
            name='mlm_distributed',
            field=models.BooleanField(default=False, verbose_name='Commissions MLM déjà distribuées'),
        ),
    ]
