# Generated by Django 5.0.7 on 2025-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_options_order_mlm_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_driver_partner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant livreur (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_laundry_partner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant blanchisseur (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_delivery_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission FAGNI livraison HT (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_laundry_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission FAGNI lavage HT (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='fagni_revenue_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenu FAGNI HT (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='fagni_revenue_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Revenu FAGNI TTC (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='prestation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total prestations modèle FAGNI (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_client_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total client TTC (modèle FAGNI, FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_fagni',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA FAGNI (FCFA)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service FAGNI (HT, FCFA)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total prestations (base)'),
        ),
    ]
