# Generated by Django 5.0.7 on 2025-12-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_amount_driver_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Ex : carte, mobile money, OM, Moov, etc.', max_length=50, null=True, verbose_name='Moyen de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Référence renvoyée par la passerelle de paiement.', max_length=120, null=True, verbose_name='Référence paiement (PSP)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée'), ('refunded', 'Remboursée'), ('partially_refunded', 'Partiellement remboursée')], default='unpaid', max_length=30, verbose_name='Statut de paiement'),
        ),
    ]
