# Generated by Django 5.0.7 on 2025-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_payment_date_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallets_distributed',
            field=models.BooleanField(default=False, verbose_name='Montants distribués dans les wallets'),
        ),
    ]
