# Generated by Django 5.0.7 on 2025-12-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_wallets_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant effectivement payé (TTC, FCFA)'),
        ),
    ]
