# Generated by Django 5.0.7 on 2025-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, help_text="Adresse de livraison (si différente de l'adresse client).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km_delivery',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance retour (blanchisserie → client) en km.', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km_pickup',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance aller (client → blanchisserie) en km.', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance totale parcourue sur la course.', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(blank=True, help_text="Adresse de collecte (si différente de l'adresse client).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
