# Generated by Django 5.0.7 on 2025-12-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_delivery_address_order_delivery_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuration par défaut', max_length=150, verbose_name='Nom de la configuration')),
                ('city', models.CharField(blank=True, help_text='Ex : Abidjan, Bouaké… (facultatif pour l’instant).', max_length=100, null=True, verbose_name='Ville / zone (optionnel)')),
                ('is_active', models.BooleanField(default=True, help_text='Une seule config active sera utilisée par défaut.', verbose_name='Configuration active')),
                ('pickup_cutoff_hour', models.PositiveSmallIntegerField(default=10, help_text='Heure limite (0–23). Si collecte après cette heure, il est difficile de garantir le 24h/48h.', verbose_name='Heure limite collecte (cutoff)')),
                ('standard_sla_hours', models.PositiveIntegerField(default=48, help_text='Délai cible (en heures) pour la formule standard.', verbose_name='Délai standard (heures)')),
                ('express_sla_hours', models.PositiveIntegerField(default=24, help_text='Délai cible (en heures) pour la formule express.', verbose_name='Délai express (heures)')),
                ('express_enabled', models.BooleanField(default=True, verbose_name='Activer la livraison express')),
                ('express_extra_flat', models.DecimalField(decimal_places=2, default=0, help_text='Ex : 1000 FCFA de plus pour une livraison express.', max_digits=10, verbose_name='Supplément express (montant fixe, FCFA)')),
                ('express_extra_percent', models.DecimalField(decimal_places=2, default=0, help_text='Ex : 10 = 10%% du montant de base. Peut être 0.', max_digits=5, verbose_name='Supplément express (% du total prestations + service FAGNI)')),
                ('scheduled_slots_enabled', models.BooleanField(default=True, verbose_name='Activer la livraison programmée')),
                ('scheduled_window_start_hour', models.PositiveSmallIntegerField(default=8, verbose_name='Heure début créneaux programmés')),
                ('scheduled_window_end_hour', models.PositiveSmallIntegerField(default=20, verbose_name='Heure fin créneaux programmés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Configuration logistique',
                'verbose_name_plural': 'Configurations logistiques',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('standard', 'Livraison standard'), ('express', 'Livraison express'), ('scheduled', 'Livraison programmée')], default='standard', help_text='Standard 48h, express 24h ou livraison programmée.', max_length=20, verbose_name='Mode de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_mode',
            field=models.CharField(choices=[('now', 'Collecte immédiate'), ('later', 'Collecte programmée')], default='now', help_text='Immédiate ou programmée.', max_length=20, verbose_name='Mode de collecte'),
        ),
    ]
