# Generated by Django 5.0.7 on 2025-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_logisticsconfig_order_delivery_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scheduled_pickup_at',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date livraison programmée'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure livraison programmée'),
        ),
        migrations.AddField(
            model_name='order',
            name='express_extra_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part du total client liée au mode express (si applicable).', max_digits=10, verbose_name='Supplément express (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date collecte programmée'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure collecte programmée'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_at',
            field=models.DateTimeField(blank=True, help_text='Utilisé uniquement si la livraison est programmée.', null=True, verbose_name='Date/heure de livraison programmée'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='express_extra_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ex : 10 = 10% du montant de base. Peut être 0.', max_digits=5, verbose_name='Supplément express (% du total prestations + service FAGNI)'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='express_sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='Délai cible (en heures) pour la formule express (ex : 24h).', verbose_name='Délai express (heures)'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='pickup_cutoff_hour',
            field=models.PositiveSmallIntegerField(default=10, help_text='Heure limite (0–23). Si la collecte est effectuée après cette heure, il sera plus difficile de garantir le 24h/48h.', verbose_name='Heure limite collecte (cutoff)'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='scheduled_window_end_hour',
            field=models.PositiveSmallIntegerField(default=20, help_text='Heure (0–23) à partir de laquelle on arrête les créneaux programmés.', verbose_name='Heure fin créneaux programmés'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='scheduled_window_start_hour',
            field=models.PositiveSmallIntegerField(default=8, help_text='Heure (0–23) à partir de laquelle on propose des créneaux programmés.', verbose_name='Heure début créneaux programmés'),
        ),
        migrations.AlterField(
            model_name='logisticsconfig',
            name='standard_sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='Délai cible (en heures) pour la formule standard (ex : 48h).', verbose_name='Délai standard (heures)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('scheduled', 'Programmée')], default='standard', max_length=20, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_mode',
            field=models.CharField(choices=[('now', 'Immédiate (dès que possible)'), ('later', 'Programmée')], default='now', max_length=20, verbose_name='Mode de collecte'),
        ),
    ]
