# Generated by Django 5.0.7 on 2025-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_order_scheduled_pickup_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_assignment_mode', models.CharField(choices=[('auto', 'Automatique'), ('manual', 'Manuelle'), ('hybrid', 'Hybride')], default='auto', max_length=16, verbose_name="Mode d'assignation livreur")),
                ('max_concurrent_orders_per_driver', models.PositiveIntegerField(default=5, verbose_name='Max de commandes simultanées par livreur')),
                ('driver_radius_km', models.DecimalField(decimal_places=2, default=15.0, help_text='Distance max entre le livreur et le point de collecte/blanchisserie.', max_digits=6, verbose_name='Rayon max pour assigner un livreur (km)')),
                ('prefer_same_driver_for_round_trip', models.BooleanField(default=True, verbose_name="Privilégier le même livreur pour l'A/R")),
                ('laundry_selection_mode', models.CharField(choices=[('closest', 'Blanchisserie la plus proche'), ('priority', 'Blanchisserie prioritaire'), ('manual', 'Sélection manuelle')], default='closest', max_length=16, verbose_name='Mode de sélection blanchisserie')),
                ('max_daily_orders_per_laundry', models.PositiveIntegerField(default=50, verbose_name='Max de commandes / jour / blanchisserie')),
                ('laundry_priority_strategy', models.CharField(blank=True, help_text="Ex : 'premium_dabord', 'equilibrage_volume', etc. Pour usage ultérieur.", max_length=128, verbose_name='Stratégie de priorité blanchisserie (texte court)')),
            ],
            options={
                'verbose_name': "Paramètres d'assignation",
                'verbose_name_plural': "Paramètres d'assignation",
            },
        ),
        migrations.CreateModel(
            name='GlobalPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Pourcentage appliqué sur le sous-total prestations.', max_digits=5, verbose_name='Taux service FAGNI (%)')),
                ('service_fee_min', models.PositiveIntegerField(default=500, help_text='Montant minimal de service FAGNI si le calcul en % est inférieur.', verbose_name='Minimum service FAGNI (FCFA)')),
                ('rounding_step', models.PositiveIntegerField(default=25, help_text="Arrondi des montants (ex : 25 FCFA). 0 = pas d'arrondi spécifique.", verbose_name="Pas d'arrondi (FCFA)")),
                ('apply_service_on_delivery', models.BooleanField(default=False, help_text='Si coché, la base de calcul inclut aussi les frais de livraison.', verbose_name='Appliquer le service aussi sur les frais de livraison')),
                ('delivery_min_fee', models.PositiveIntegerField(default=2000, help_text='Montant minimal facturé pour une livraison, si il y a au moins une prestation.', verbose_name='Frais livraison minimum (FCFA)')),
                ('delivery_price_per_km', models.DecimalField(decimal_places=2, default=150.0, help_text='Montant par km aller-retour pour calculer la livraison.', max_digits=7, verbose_name='Prix par km (AR) (FCFA)')),
                ('delivery_fixed_fee', models.PositiveIntegerField(default=0, help_text='Surcoût fixe ajouté aux frais de livraison (ex : péage, zone, plateforme…).', verbose_name='Frais fixes livraison (FCFA)')),
                ('delivery_free_threshold', models.PositiveIntegerField(default=0, help_text='Au-dessus de ce total TTC client, la livraison peut être offerte (0 = désactivé).', verbose_name='Seuil de livraison offerte (FCFA)')),
                ('express_extra_fixed', models.PositiveIntegerField(default=0, help_text='Montant fixe ajouté pour une livraison express.', verbose_name='Supplément express fixe (FCFA)')),
                ('express_extra_percent', models.DecimalField(decimal_places=2, default=0.0, help_text="Pourcentage sur le sous-total prestations pour l'express (0 = désactivé).", max_digits=5, verbose_name='Supplément express (%)')),
                ('express_extra_target', models.CharField(choices=[('LAUNDRY', 'Blanchisserie'), ('FAGNI', 'FAGNI'), ('DRIVER', 'Livreur'), ('SPLIT', 'Répartition (pour plus tard)')], default='LAUNDRY', help_text='Où va le supplément express (par défaut : blanchisserie).', max_length=16, verbose_name='Bénéficiaire du supplément express')),
                ('express_affects_customer_price', models.BooleanField(default=True, help_text='Si décoché, le supplément est pris par FAGNI sans augmenter le TTC client.', verbose_name='Répercuter le supplément express sur le client')),
                ('driver_share_ratio', models.DecimalField(decimal_places=2, default=70.0, help_text='Pourcentage des frais de livraison (hors service FAGNI) reversé au livreur.', max_digits=5, verbose_name='Part livreur sur la livraison (%)')),
                ('driver_min_fee', models.PositiveIntegerField(default=1000, help_text='Plancher de rémunération livreur par commande livrée.', verbose_name='Minimum par course pour le livreur (FCFA)')),
                ('logistic_margin_ratio', models.DecimalField(decimal_places=2, default=30.0, help_text='Part des frais de livraison gardée par FAGNI (en pratique 100 - part livreur).', max_digits=5, verbose_name='Marge logistique FAGNI sur la livraison (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Taux de TVA appliqué sur les revenus FAGNI.', max_digits=5, verbose_name='TVA (%)')),
                ('apply_vat_on_service_only', models.BooleanField(default=True, help_text="Si décoché, la TVA pourra être calculée sur d'autres composantes plus tard.", verbose_name='Appliquer la TVA uniquement sur les revenus FAGNI')),
            ],
            options={
                'verbose_name': 'Paramètres globaux de pricing',
                'verbose_name_plural': 'Paramètres globaux de pricing',
            },
        ),
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_pickup_mode', models.CharField(choices=[('immediate', 'Immédiate (dès que possible)'), ('scheduled', 'Programmée')], default='immediate', max_length=16, verbose_name='Mode de collecte par défaut')),
                ('standard_sla_hours', models.PositiveIntegerField(default=48, help_text='Délai cible en heures entre collecte et livraison en mode standard.', verbose_name='SLA standard (heures)')),
                ('express_sla_hours', models.PositiveIntegerField(default=24, help_text="Délai cible en heures pour l'express (déjà utilisé dans le front).", verbose_name='SLA express (heures)')),
                ('max_sla_days', models.PositiveIntegerField(default=7, help_text="Au-delà de ce délai, on considère que la livraison est 'programmée long terme'.", verbose_name='Délai max en jours')),
                ('pickup_cutoff_hour', models.PositiveIntegerField(default=10, help_text="Ex : avant 10h, on peut encore garantir l'express le lendemain.", verbose_name='Heure limite collecte pour express (h)')),
                ('same_day_delivery_allowed', models.BooleanField(default=False, help_text='Si activé, permet des flux ultra-rapides dans certaines zones.', verbose_name='Autoriser la livraison le jour même')),
                ('require_pickup_done_before_delivery_leg_start', models.BooleanField(default=True, help_text="Empêche un livreur de démarrer un tronçon retour si l'aller n'est pas terminé.", verbose_name='Exiger la collecte avant de démarrer la livraison')),
                ('require_laundry_validation_before_delivery_assignment', models.BooleanField(default=True, help_text="Si activé, la jambe 'blanchisserie → client' n'est assignée/démarrable qu'après validation du blanchisseur.", verbose_name="Exiger validation blanchisserie avant l'assignation livraison")),
                ('allow_cancel_after_pickup', models.BooleanField(default=False, help_text='Si vrai, il faudra éventuellement gérer des pénalités.', verbose_name='Autoriser une annulation après collecte')),
                ('cancel_penalty_customer_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage du montant à conserver si le client annule tardivement.', max_digits=5, verbose_name="Pénalité client en cas d'annulation (%)")),
                ('cancel_penalty_driver_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage potentiellement retenu sur le livreur (pour futur).', max_digits=5, verbose_name='Pénalité livreur en cas de no-show (%)')),
            ],
            options={
                'verbose_name': 'Paramètres de workflow',
                'verbose_name_plural': 'Paramètres de workflow',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('scheduled', 'Programmée')], default='standard', help_text='Standard 48h, express 24h ou livraison programmée.', max_length=20, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_mode',
            field=models.CharField(choices=[('now', 'Immédiate (dès que possible)'), ('later', 'Programmée')], default='now', help_text='Immédiate ou programmée.', max_length=20, verbose_name='Mode de collecte'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_delivery_at',
            field=models.DateTimeField(blank=True, help_text='Ancien champ – pourra être supprimé plus tard au profit des champs date/heure séparés.', null=True, verbose_name='Date/heure de livraison programmée (legacy)'),
        ),
    ]
