# Generated by Django 5.0.7 on 2025-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_assignmentsettings_globalpricingsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(blank=True, help_text='Date d’émission officielle de la facture.', null=True, verbose_name='Date de facture'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro unique de facture FAGNI (ex: FGN-2025-000123).', max_length=30, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('canceled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut de la facture'),
        ),
    ]
