# Generated by Django 5.0.7 on 2025-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_invoice_date_order_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant HT soumis à TVA (revenu FAGNI uniquement).', max_digits=10, verbose_name='Base taxable TVA (FCFA)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Taux de TVA appliqué au revenu FAGNI.', max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
