# Generated by Django 5.0.7 on 2025-12-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_vat_base_order_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro de facture FAGNI (généré automatiquement au paiement).', max_length=30, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
    ]
