# Generated by Django 5.0.7 on 2025-12-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_order_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='FAGNI', max_length=150, verbose_name='Nom société')),
                ('company_tagline', models.CharField(blank=True, max_length=200, null=True, verbose_name='Slogan (optionnel)')),
                ('header_logo', models.ImageField(blank=True, help_text='Logo affiché sur les factures/tickets PDF.', null=True, upload_to='invoice/', verbose_name='Logo (en-tête)')),
                ('company_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('header_note', models.CharField(blank=True, help_text='Ex : “Facture émise par FAGNI GROUP SAS”.', max_length=255, null=True, verbose_name='Note en-tête (optionnel)')),
                ('footer_text', models.TextField(blank=True, help_text='Mentions légales, conditions, remerciements, etc.', null=True, verbose_name='Pied de page (footer)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
            ],
            options={
                'verbose_name': 'Paramètres facture (en-tête/footer)',
                'verbose_name_plural': 'Paramètres facture (en-tête/footer)',
            },
        ),
    ]
