# Generated by Django 5.0.7 on 2025-12-14 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_invoicesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicesettings',
            options={'verbose_name': 'Paramètres facture (en-tête/pied)', 'verbose_name_plural': 'Paramètres facture (en-tête/pied)'},
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créée le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_name',
            field=models.CharField(default='FAGNI', max_length=150, verbose_name='Nom entreprise'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='company_tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texte pied de page'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='invoice/logo/', verbose_name='Logo (en-tête)'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='header_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note en-tête'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
    ]
