# Generated by Django 5.0.7 on 2025-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fne_error',
            field=models.TextField(blank=True, help_text='Message d’erreur si rejet/erreur technique.', null=True, verbose_name='Erreur FNE'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_invoice_number',
            field=models.CharField(blank=True, help_text='Numéro renvoyé par la plateforme FNE après émission/validation.', max_length=64, null=True, verbose_name='N° FNE (numéro normalisé)'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_payload',
            field=models.JSONField(blank=True, help_text='Copie du payload envoyé / réponse (audit interne).', null=True, verbose_name='Payload FNE (audit)'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_qr_data',
            field=models.TextField(blank=True, help_text='Données/URL QR officiel FNE (si fourni).', null=True, verbose_name='Données QR FNE'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FNE envoyée le'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_status',
            field=models.CharField(choices=[('disabled', 'Désactivée'), ('pending', 'À envoyer'), ('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('error', 'Erreur')], default='disabled', help_text='Suivi interne de la synchro FNE (sans intégration API pour l’instant).', max_length=20, verbose_name='Statut FNE'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_synced_at',
            field=models.DateTimeField(blank=True, help_text='Date de retour/confirmation (acceptée/rejetée).', null=True, verbose_name='FNE synchronisée le'),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_uid',
            field=models.CharField(blank=True, help_text='Identifiant unique retourné par la plateforme FNE (si applicable).', max_length=128, null=True, verbose_name='UID FNE'),
        ),
    ]
