# Generated by Django 5.0.7 on 2025-12-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_fne_error_order_fne_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Numéro unique de facture FAGNI (ex: FGN-2025-000123).', max_length=30, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
    ]
