# Generated by Django 5.0.7 on 2026-01-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_order_invoice_number'),
        ('partners', '0005_seed_demo_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryleg',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_legs', to='partners.deliverypartner', verbose_name='Livreur partenaire'),
        ),
    ]
