# Generated by Django 5.0.7 on 2026-01-21 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_deliveryleg_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payée'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('refunded', 'Remboursée'), ('partially_refunded', 'Partiellement remboursée')], default='unpaid', max_length=30, verbose_name='Statut de paiement'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('order', 'reference'), name='uniq_payment_order_reference_nonempty'),
        ),
    ]
