# Generated by Django 5.0.7 on 2026-02-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(choices=[('essential', 'Essentiel'), ('comfort', 'Confort')], default='essential', max_length=20, verbose_name='Pack')),
                ('bag_size', models.CharField(choices=[('S', 'Sac S'), ('M', 'Sac M')], default='M', max_length=2, verbose_name='Taille sac')),
                ('pickup_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0, help_text='Jour fixe de collecte hebdomadaire.', verbose_name='Jour collecte')),
                ('delivery_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=3, help_text='Jour fixe de livraison hebdomadaire.', verbose_name='Jour livraison')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notes (optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='Semaine (lundi)')),
                ('pickup_date', models.DateField(db_index=True, verbose_name='Date collecte')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='Date livraison')),
                ('bag_size', models.CharField(default='M', max_length=2, verbose_name='Taille sac')),
                ('status', models.CharField(choices=[('COLLECTE', 'À collecter'), ('EN_TRAITEMENT', 'En traitement'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='COLLECTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Cycle abonnement',
                'verbose_name_plural': 'Cycles abonnement',
                'ordering': ['-pickup_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_payment_order_reference_nonempty',
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='orders.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subscriptioncycle',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_cycles', to='orders.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subscriptioncycle',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cycles', to='orders.order', verbose_name='Commande liée (optionnel)'),
        ),
        migrations.AddField(
            model_name='subscriptioncycle',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='orders.subscription', verbose_name='Abonnement'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncycle',
            constraint=models.UniqueConstraint(fields=('subscription', 'week_start'), name='uniq_subscription_week_start'),
        ),
    ]
