# Generated by Django 5.0.7 on 2026-02-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_add_wallettransaction_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWeighing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scale_photo', models.ImageField(blank=True, null=True, upload_to='orders/weighing/')),
                ('entered_by_type', models.CharField(choices=[('driver', 'Livreur'), ('laundry', 'Blanchisserie'), ('ops', 'Ops/FAGNI')], max_length=16)),
                ('entered_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_by_other', models.BooleanField(default=False)),
                ('confirmed_by_type', models.CharField(blank=True, default='', max_length=16)),
                ('confirmed_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('disputed', 'Contestée')], default='draft', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weighing', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('client', 'Client'), ('driver', 'Livreur'), ('laundry', 'Blanchisserie'), ('ops', 'Ops/FAGNI')], max_length=16)),
                ('actor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('pickup_items', 'Articles au départ (preuve)'), ('bag_before_seal', 'Sac avant scellage'), ('bag_sealed', 'Sac scellé'), ('weighing_scale', 'Photo balance (pesée)'), ('dropoff_to_laundry', 'Dépôt chez blanchisseur'), ('return_from_laundry', 'Retour depuis blanchisseur'), ('delivery_to_client', 'Livraison au client'), ('issue', 'Litige / anomalie')], max_length=32)),
                ('image', models.ImageField(upload_to='orders/evidence/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_photos', to='orders.deliveryleg')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_photos', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'kind', 'created_at'], name='orders_orde_order_i_bb1ec9_idx'), models.Index(fields=['actor_type', 'created_at'], name='orders_orde_actor_t_843805_idx')],
            },
        ),
    ]
