# Generated by Django 5.0.7 on 2026-02-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_orderweighing_orderevidencephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderweighing',
            name='final_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderweighing',
            name='resolution_notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orderweighing',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderweighing',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_weighings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderweighing',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('disputed', 'Contestée'), ('resolved', 'Résolue OPS')], default='draft', max_length=16),
        ),
    ]
