# Generated by Django 5.0.7 on 2026-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_orderweighing_final_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncycle',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, help_text='Commande en cours de création côté client (wizard).', verbose_name='Brouillon'),
        ),
    ]
