# Generated by Django 5.0.7 on 2026-02-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_subscriptioncycle_is_draft'),
        ('partners', '0005_seed_demo_partners'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryleg',
            constraint=models.UniqueConstraint(fields=('order', 'leg_type'), name='uniq_leg_per_order_type'),
        ),
    ]
