# Generated by Django 5.0.7 on 2026-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_orderrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, help_text='Commande en cours de création côté client (wizard).', verbose_name='Brouillon'),
        ),
    ]
