# Generated by Django 5.0.7 on 2026-02-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_order_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=20)),
                ('event_type', models.CharField(choices=[('checkout_created', 'Checkout créé'), ('payment_succeeded', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('refund', 'Remboursement')], max_length=40)),
                ('provider_reference', models.CharField(help_text='ID unique côté PSP (checkout_id, transaction_id, event_id, etc.)', max_length=120)),
                ('payload', models.JSONField(blank=True, help_text='Payload brut reçu du PSP (webhook).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_reference'], name='orders_paym_provide_7752f6_idx'), models.Index(fields=['status'], name='orders_paym_status_da05f2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_reference'), name='uniq_provider_reference_event'),
        ),
    ]
