# Generated by Django 5.0.7 on 2026-02-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_paymentevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
