# Generated by Django 5.0.7 on 2026-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_paymentevent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryleg',
            name='client_signature',
            field=models.TextField(blank=True, help_text='Signature client encodée en base64 (data:image/png;base64,...) — MVP.', null=True, verbose_name='Signature client (base64 PNG)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signature prise le'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='delivered_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat livraison (POD)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='delivered_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Lng livraison (POD)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='delivery_otp',
            field=models.CharField(blank=True, db_index=True, help_text='Code OTP à confirmer par le client pour valider la livraison (jambe return).', max_length=6, null=True, verbose_name='OTP livraison (6 chiffres)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='delivery_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP livraison'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP vérifié le'),
        ),
    ]
