# Generated by Django 5.0.7 on 2026-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_deliveryleg_client_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryleg',
            name='picked_up_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat collecte (POP)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='picked_up_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Lng collecte (POP)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='pickup_otp',
            field=models.CharField(blank=True, db_index=True, help_text='Code OTP à confirmer par le client pour valider la collecte (jambe pickup).', max_length=6, null=True, verbose_name='OTP collecte (6 chiffres)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='pickup_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration OTP collecte'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='pickup_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP collecte vérifié le'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='pickup_signature',
            field=models.TextField(blank=True, help_text='Signature client à la collecte encodée en base64 (data:image/png;base64,...) — MVP.', null=True, verbose_name='Signature collecte (base64 PNG)'),
        ),
        migrations.AddField(
            model_name='deliveryleg',
            name='pickup_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signature collecte prise le'),
        ),
    ]
