# Generated by Django 5.0.7 on 2026-02-27 12:31
from django.db import migrations, models
from django.utils.text import slugify


def _make_unique(base: str, used: set[str]) -> str:
    base = (base or "").strip() or "item"
    cand = base[:100]
    i = 2
    while cand in used:
        suffix = f"-{i}"
        cand = (base[: (100 - len(suffix))] + suffix)[:100]
        i += 1
    used.add(cand)
    return cand


def forwards(apps, schema_editor):
    ServiceItem = apps.get_model("orders", "ServiceItem")

    used = set()

    for it in ServiceItem.objects.all().order_by("id"):
        raw = getattr(it, "code", None)
        code = (str(raw).strip() if raw is not None else "")

        # On garde le premier code non vide rencontré
        if code and code not in used:
            used.add(code)
            continue

        cat = getattr(it, "category", None)
        cat_slug = getattr(cat, "slug", None) if cat else None
        if not cat_slug:
            cat_id = getattr(it, "category_id", None)
            cat_slug = f"cat{cat_id or 'x'}"

        name = getattr(it, "name", None) or "service"
        base = slugify(f"{cat_slug}-{name}") or "service"

        new_code = _make_unique(base, used)
        setattr(it, "code", new_code)
        it.save(update_fields=["code"])


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0054_deliveryleg_picked_up_lat_deliveryleg_picked_up_lng_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="serviceitem",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
