# Generated by Django 5.0.7 on 2026-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_deliveryleg_picked_up_lat_deliveryleg_picked_up_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
