# Generated by Django 5.0.7 on 2026-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0055_alter_serviceitem_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "À déduire"),
                    ("pressing", "Pressing"),
                    ("cordonnerie", "Cordonnerie"),
                    ("chaussures", "Chaussures"),
                    ("retouche", "Retouche"),
                ],
                db_index=True,
                default="",
                help_text="Champ canonique FAGNI (pressing, cordonnerie, chaussures, retouche).",
                max_length=32,
                verbose_name="Type de service canonique",
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Code interne"
            ),
        ),
    ]
