# Generated by Django 5.0.7 on 2026-04-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0056_orderitem_service_type_alter_serviceitem_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
