# Generated by Django 5.0.7 on 2026-04-02 13:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0057_order_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpsell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "express_24h",
                    models.BooleanField(default=False, verbose_name="Express 24h"),
                ),
                (
                    "premium_ironing",
                    models.BooleanField(
                        default=False, verbose_name="Repassage premium"
                    ),
                ),
                (
                    "fragrance",
                    models.BooleanField(default=False, verbose_name="Parfum linge"),
                ),
                (
                    "delicate_care",
                    models.BooleanField(default=False, verbose_name="Soin délicat"),
                ),
                (
                    "express_24h_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000.00"),
                        max_digits=12,
                        verbose_name="Frais express 24h",
                    ),
                ),
                (
                    "premium_ironing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=12,
                        verbose_name="Frais repassage premium",
                    ),
                ),
                (
                    "fragrance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("300.00"),
                        max_digits=12,
                        verbose_name="Frais parfum linge",
                    ),
                ),
                (
                    "delicate_care_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=12,
                        verbose_name="Frais soin délicat",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upsell commande",
                "verbose_name_plural": "Upsells commande",
            },
        ),
    ]
