# Generated by Django 5.0.7 on 2026-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0058_orderupsell"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bag_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Petit sac"),
                    ("medium", "Sac moyen"),
                    ("large", "Grand sac"),
                ],
                db_index=True,
                help_text="Utilisé uniquement si pricing_mode='bag'.",
                max_length=10,
                null=True,
                verbose_name="Taille de sac",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pricing_mode",
            field=models.CharField(
                choices=[("bag", "Sac"), ("item", "À la pièce")],
                db_index=True,
                default="bag",
                help_text="Mode d'entrée client : sac rapide ou détail à la pièce.",
                max_length=10,
                verbose_name="Mode de tarification",
            ),
        ),
    ]
