# Generated by Django 5.0.7 on 2026-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0059_order_bag_size_order_pricing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpricingsettings",
            name="laundry_commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Pourcentage prélevé par FAGNI sur la prestation blanchisserie.",
                max_digits=5,
                verbose_name="Commission FAGNI sur prestation (%)",
            ),
        ),
    ]
