# Generated by Django 5.0.7 on 2026-04-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0060_globalpricingsettings_laundry_commission_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="service_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
