# Generated by Django 5.0.7 on 2026-04-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0061_order_service_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_declared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_declared_channel",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_declared_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Aucune"),
                    ("pending_review", "En attente de revue"),
                    ("verified", "Vérifié"),
                    ("rejected", "Rejeté"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Non payée"),
                    ("partial", "Partiellement payée"),
                    ("paid", "Payée"),
                    ("refunded", "Remboursée"),
                    ("partially_refunded", "Partiellement remboursée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
