# Generated by Django 5.0.7 on 2026-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0062_order_payment_declared_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
