# Generated by Django 5.0.7 on 2026-04-23 20:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0063_waveevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("wave_webhook", "Wave webhook"),
                            ("wave_ops", "Wave OPS"),
                            ("cash", "Cash"),
                            ("manual", "Manuel"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant appliqué",
                    ),
                ),
                (
                    "amount_paid_before",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant payé avant",
                    ),
                ),
                (
                    "amount_paid_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant payé après",
                    ),
                ),
                (
                    "status_before",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Statut avant",
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Statut après",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_events",
                        to="orders.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de paiement commande",
                "verbose_name_plural": "Événements de paiement commande",
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"],
                        name="orders_orde_order_i_798d5c_idx",
                    ),
                    models.Index(
                        fields=["channel", "reference"],
                        name="orders_orde_channel_b10520_idx",
                    ),
                ],
            },
        ),
    ]
