# Generated by Django 5.0.7 on 2026-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0064_orderpaymentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.FileField(
                blank=True,
                help_text="Capture ou preuve du paiement Wave envoyée par le client.",
                null=True,
                upload_to="payment_proofs/",
                verbose_name="Preuve de paiement",
            ),
        ),
    ]
