# Generated by Django 5.0.7 on 2026-05-12 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0065_order_payment_proof"),
        ("partners", "0007_remove_deliverypartner_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderrating",
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatushistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Historique statut",
                "verbose_name_plural": "Historiques statuts",
            },
        ),
        migrations.AlterModelOptions(
            name="orderweighing",
            options={"verbose_name": "Pesée", "verbose_name_plural": "Pesées"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Paiement", "verbose_name_plural": "Paiements"},
        ),
        migrations.AlterModelOptions(
            name="paymentevent",
            options={
                "verbose_name": "Événement paiement",
                "verbose_name_plural": "Événements paiement",
            },
        ),
        migrations.AlterModelOptions(
            name="waveevent",
            options={
                "verbose_name": "Événement Wave",
                "verbose_name_plural": "Événements Wave",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_orders",
                to="partners.deliverypartner",
                verbose_name="Livreur collecte",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryleg",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legs",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="partners.deliverypartner",
                verbose_name="Livreur livraison",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_declared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Déclaré le"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_declared_channel",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Canal déclaré"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_declared_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Référence déclarée",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Non payée"),
                    ("partial", "Partiellement payée"),
                    ("paid", "Payée"),
                    ("refunded", "Remboursée"),
                    ("partially_refunded", "Partiellement remboursée"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Aucune"),
                    ("pending_review", "En attente de revue"),
                    ("verified", "Vérifié"),
                    ("rejected", "Rejeté"),
                ],
                default="none",
                max_length=20,
                verbose_name="Statut vérification",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifié le"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Latitude collecte"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Longitude collecte"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("in_progress", "En cours"),
                    ("done", "Terminée"),
                    ("canceled", "Annulée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderevidencephoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.serviceitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemphoto",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="orders.orderitem",
            ),
        ),
        migrations.AlterField(
            model_name="orderpaymentevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_events",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderrating",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Commentaire"
            ),
        ),
        migrations.AlterField(
            model_name="orderrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="orderrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="orderupsell",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upsell",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="notes",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Notes"
            ),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="resolution_notes",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Notes de résolution",
            ),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Résolu le"),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("confirmed", "Confirmée"),
                    ("disputed", "Contestée"),
                    ("resolved", "Résolue OPS"),
                ],
                default="draft",
                max_length=16,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="orderweighing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("checkout_created", "Checkout créé"),
                    ("payment_succeeded", "Paiement réussi"),
                    ("payment_failed", "Paiement échoué"),
                    ("refund", "Remboursement"),
                ],
                max_length=40,
                verbose_name="Type d'événement",
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("ignored", "Ignored"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="orders.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="orders.customer",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycle",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_cycles",
                to="orders.customer",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycle",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_cycles",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioncycle",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="orders.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="waveevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
    ]
