# Generated by Django 5.0.7 on 2026-05-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0066_add_pickup_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bag_size",
                    models.CharField(
                        choices=[
                            ("small", "Petit sac"),
                            ("medium", "Sac moyen"),
                            ("large", "Grand sac"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Taille sac",
                    ),
                ),
                (
                    "pressing_amount",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Prix pressing (FCFA)"
                    ),
                ),
                (
                    "delivery_fee",
                    models.PositiveIntegerField(
                        default=2000, verbose_name="Frais livraison (FCFA)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Label affiché"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration prix",
                "verbose_name_plural": "Configuration des prix",
                "ordering": ["pressing_amount"],
            },
        ),
    ]
