# Generated by Django 5.0.7 on 2026-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0067_add_pricing_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID article"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "emoji",
                    models.CharField(default="👕", max_length=10, verbose_name="Emoji"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hauts", "Hauts"),
                            ("bas", "Bas"),
                            ("robes", "Robes & Ensembles"),
                            ("vestes", "Vestes & Manteaux"),
                            ("accessoires", "Accessoires"),
                            ("linge", "Linge de maison"),
                        ],
                        default="hauts",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "slots",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Slots (place dans le sac)"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.3,
                        max_digits=4,
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Quantité max par commande"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article catalogue",
                "verbose_name_plural": "Articles catalogue",
                "ordering": ["category", "sort_order", "label"],
            },
        ),
    ]
