# Generated by Django 5.0.7 on 2026-05-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0068_add_article_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleconfig",
            name="prix_unitaire",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Prix unitaire FCFA (si sur devis)"
            ),
        ),
        migrations.AddField(
            model_name="articleconfig",
            name="sur_devis",
            field=models.BooleanField(
                default=False, verbose_name="Sur devis (validation OPS)"
            ),
        ),
    ]
