# Generated by Django 5.0.7 on 2026-05-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0069_add_sur_devis_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfig",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=30.0,
                max_digits=5,
                verbose_name="Commission FAGNI (%)",
            ),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="partner_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=70.0,
                max_digits=5,
                verbose_name="Part pressing (%)",
            ),
        ),
    ]
