# Generated by Django 5.0.7 on 2026-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0070_add_commission_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partenaire_type",
                    models.CharField(
                        choices=[("pressing", "Pressing"), ("livreur", "Livreur")],
                        max_length=20,
                    ),
                ),
                ("partenaire_id", models.PositiveIntegerField()),
                ("partenaire_nom", models.CharField(max_length=200)),
                ("montant", models.PositiveIntegerField()),
                ("nb_commandes", models.PositiveIntegerField(default=0)),
                ("wave_number", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="OPS", max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
