# Generated by Django 5.0.7 on 2026-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0071_add_paiement_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parrainage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parrain_type",
                    models.CharField(
                        choices=[
                            ("client", "Client → Client"),
                            ("livreur", "Livreur → Livreur"),
                            ("pressing", "Pressing → Pressing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parrain_id", models.PositiveIntegerField()),
                ("parrain_nom", models.CharField(max_length=200)),
                (
                    "filleul_type",
                    models.CharField(
                        choices=[
                            ("client", "Client → Client"),
                            ("livreur", "Livreur → Livreur"),
                            ("pressing", "Pressing → Pressing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filleul_id", models.PositiveIntegerField(blank=True, null=True)),
                ("filleul_nom", models.CharField(blank=True, max_length=200)),
                ("filleul_phone", models.CharField(blank=True, max_length=20)),
                ("code_parrainage", models.CharField(max_length=20, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("invite", "Invité"),
                            ("inscrit", "Inscrit"),
                            ("actif", "Actif — récompense déclenchée"),
                            ("paye", "Payé"),
                        ],
                        default="invite",
                        max_length=20,
                    ),
                ),
                ("nb_actions", models.PositiveIntegerField(default=0)),
                ("actions_requises", models.PositiveIntegerField(default=10)),
                ("score_bonus", models.PositiveIntegerField(default=10)),
                ("remuneration_parrain", models.PositiveIntegerField(default=0)),
                ("remuneration_filleul", models.PositiveIntegerField(default=0)),
                ("cash_active", models.BooleanField(default=False)),
                ("cash_paye", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
