# Generated by Django 5.0.7 on 2026-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0072_add_parrainage_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="articles_count",
            field=models.IntegerField(default=0, verbose_name="Nb articles réels"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expiration paiement"
            ),
        ),
    ]
