# Generated by Django 5.0.7 on 2026-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0074_rentability_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fagnievent",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("driver", "Livreur"),
                    ("partner", "Pressing"),
                    ("ops", "OPS"),
                    ("system", "Système"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fagnievent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="fagnievent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order.created", "Commande créée"),
                    ("payment.paid", "Paiement reçu"),
                    ("pickup.assigned", "Livreur collecte assigné"),
                    ("pickup.started", "Collecte démarrée"),
                    ("pickup.done", "Collecte confirmée"),
                    ("pressing.received", "Pressing reçu"),
                    ("pressing.done", "Pressing terminé"),
                    ("delivery.assigned", "Livreur livraison assigné"),
                    ("delivery.started", "Livraison démarrée"),
                    ("delivery.done", "Livraison confirmée"),
                    ("order.cancelled", "Commande annulée"),
                    ("incident.reported", "Incident signalé"),
                ],
                db_index=True,
                max_length=60,
                verbose_name="Événement",
            ),
        ),
        migrations.AlterField(
            model_name="fagnievent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
