# Generated by Django 5.0.7 on 2026-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0075_alter_fagnievent_actor_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("driver", "Livreur"),
                            ("partner", "Pressing"),
                            ("ops", "OPS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Token FCM",
                "unique_together": {("user_type", "user_id")},
            },
        ),
    ]
