# Generated by Django 5.0.7 on 2026-06-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0076_fcm_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("before", "Avant traitement"),
                            ("after", "Après traitement"),
                        ],
                        max_length=10,
                    ),
                ),
                ("photo_data", models.TextField(blank=True)),
                ("uploaded_by", models.CharField(default="partner", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo commande",
                "unique_together": {("order", "photo_type")},
            },
        ),
    ]
