# Generated by Django 5.0.7 on 2026-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0077_order_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpricingsettings",
            name="driver_amount_per_leg",
            field=models.PositiveIntegerField(
                default=800,
                help_text="Montant payé au livreur pour chaque collecte ou livraison",
                verbose_name="Rémunération livreur par tronçon (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="globalpricingsettings",
            name="prix_article_fcfa",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Prix unitaire facturé au client par article",
                verbose_name="Prix par article (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="globalpricingsettings",
            name="wave_business_number",
            field=models.CharField(
                default="0748643892",
                help_text="Numéro Wave sur lequel les clients paient",
                max_length=20,
                verbose_name="Numéro Wave Business",
            ),
        ),
        migrations.AddField(
            model_name="globalpricingsettings",
            name="whatsapp_ops_number",
            field=models.CharField(
                default="0142299949",
                help_text="Numéro WhatsApp du coordinateur OPS",
                max_length=20,
                verbose_name="Numéro WhatsApp OPS",
            ),
        ),
    ]
