# Generated by Django 5.0.7 on 2026-07-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0078_pricing_fagni_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderevidencephoto",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pickup_items", "Articles au départ (preuve)"),
                    ("bag_before_seal", "Sac avant scellage"),
                    ("bag_sealed", "Sac scellé"),
                    ("weighing_scale", "Photo balance (pesée)"),
                    ("dropoff_to_laundry", "Dépôt chez blanchisseur"),
                    ("return_from_laundry", "Retour depuis blanchisseur"),
                    ("delivery_to_client", "Livraison au client"),
                    ("partner_before", "Avant traitement (pressing)"),
                    ("partner_after", "Après traitement (pressing)"),
                    ("issue", "Litige / anomalie"),
                ],
                max_length=32,
            ),
        ),
    ]
