# Generated by Django 5.0.7 on 2026-07-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0079_add_partner_photo_kinds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=30, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description interne"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Pourcentage"),
                            ("fixed", "Montant fixe (FCFA)"),
                        ],
                        default="percent",
                        max_length=10,
                        verbose_name="Type de reduction",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valeur de la reduction",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optionnel - plafonne la reduction pour un coupon en pourcentage.",
                        max_digits=10,
                        null=True,
                        verbose_name="Plafond de reduction (FCFA)",
                    ),
                ),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=True, verbose_name="Premiere commande uniquement"
                    ),
                ),
                (
                    "max_uses_per_customer",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Utilisations max par client"
                    ),
                ),
                (
                    "max_total_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optionnel - laisser vide pour illimite.",
                        null=True,
                        verbose_name="Utilisations max au total",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valide a partir de")),
                ("valid_until", models.DateTimeField(verbose_name="Valide jusqu'au")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
            ],
            options={
                "verbose_name": "Coupon de reduction",
                "verbose_name_plural": "Coupons de reduction",
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant reduit (FCFA)",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utilise le"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="orders.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="orders.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de coupon",
                "verbose_name_plural": "Utilisations de coupons",
            },
        ),
    ]
