# Generated by Django 5.0.7 on 2026-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0080_add_coupon_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                help_text="Code coupon saisi lors de la creation de la commande (ADR-025).",
                max_length=30,
                null=True,
                verbose_name="Code coupon saisi",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Reduction coupon appliquee (FCFA)",
            ),
        ),
    ]
