# Generated by Django 5.0.7 on 2026-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0081_add_order_coupon_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                ("message", models.CharField(max_length=300, verbose_name="Message")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="announcements/",
                        verbose_name="Image (optionnel)",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, default="📣", max_length=10, verbose_name="Emoji"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("valid_from", models.DateTimeField(verbose_name="Valide a partir de")),
                ("valid_until", models.DateTimeField(verbose_name="Valide jusqu'au")),
                (
                    "send_push_notification",
                    models.BooleanField(
                        default=False,
                        help_text="Coche pour notifier tous les clients au moment de l'activation (envoi unique).",
                        verbose_name="Envoyer aussi en notification push",
                    ),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Notification envoyee le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creee le"),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-created_at"],
            },
        ),
    ]
