# Generated by Django 5.0.7 on 2026-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0082_add_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp direct"),
                            ("voisinage", "Voisinage"),
                            ("residence", "Résidence"),
                            ("groupe_whatsapp", "Groupe WhatsApp"),
                            ("bouche_a_oreille", "Bouche-à-oreille"),
                            ("autre", "Autre"),
                        ],
                        default="whatsapp",
                        max_length=30,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("contacte", "Contacté"),
                            ("interesse", "Intéressé"),
                            ("commande", "1ère commande passée"),
                            ("fondateur", "Client Fondateur actif"),
                            ("perdu", "Pas intéressé"),
                        ],
                        default="contacte",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Contacté le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "ordering": ["-created_at"],
            },
        ),
    ]
