# Generated by Django 5.0.7 on 2026-07-15 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0083_add_prospect"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotBookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code_libre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Code commande (si non liee)",
                    ),
                ),
                (
                    "ce_qui_a_bien_fonctionne",
                    models.TextField(
                        blank=True, default="", verbose_name="Ce qui s'est bien passe"
                    ),
                ),
                (
                    "ce_qui_a_echoue",
                    models.TextField(
                        blank=True, default="", verbose_name="Ce qui a echoue"
                    ),
                ),
                (
                    "cause_reelle",
                    models.TextField(
                        blank=True, default="", verbose_name="Cause reelle"
                    ),
                ),
                (
                    "decision_prise",
                    models.TextField(
                        blank=True, default="", verbose_name="Decision prise"
                    ),
                ),
                (
                    "modification_apportee",
                    models.TextField(
                        blank=True, default="", verbose_name="Modification apportee"
                    ),
                ),
                (
                    "impact_mesure",
                    models.TextField(
                        blank=True, default="", verbose_name="Impact mesure"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Consigne le"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Commande liee, si applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_book_entries",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entree Pilot Book",
                "verbose_name_plural": "Pilot Book - Journal du pilote",
                "ordering": ["-created_at"],
            },
        ),
    ]
