# Generated by Django 5.0.7 on 2026-07-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0084_add_pilotbookentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pack",
                    models.CharField(
                        choices=[
                            ("essentiel", "Essentiel (lavage seul)"),
                            ("confort", "Confort (lavage + repassage)"),
                        ],
                        max_length=20,
                        verbose_name="Pack",
                    ),
                ),
                (
                    "taille_sac",
                    models.CharField(
                        choices=[("S", "Sac S"), ("M", "Sac M")],
                        max_length=2,
                        verbose_name="Taille sac",
                    ),
                ),
                (
                    "jour_collecte",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour collecte",
                    ),
                ),
                (
                    "jour_livraison",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="Jour livraison",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("resilie", "Resilie"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "prix_verrouille",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix au moment de la souscription - jamais modifie retroactivement (BOS 4.1, meme regle que Order.total_client_ttc).",
                        max_digits=10,
                        verbose_name="Prix verrouille (FCFA)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis a jour le"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abonnements",
                        to="orders.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbonnementPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pack",
                    models.CharField(
                        choices=[
                            ("essentiel", "Essentiel (lavage seul)"),
                            ("confort", "Confort (lavage + repassage)"),
                        ],
                        max_length=20,
                        verbose_name="Pack",
                    ),
                ),
                (
                    "taille_sac",
                    models.CharField(
                        choices=[("S", "Sac S"), ("M", "Sac M")],
                        max_length=2,
                        verbose_name="Taille sac",
                    ),
                ),
                (
                    "prix_hebdomadaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix hebdomadaire (FCFA)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Actif commercialement"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notes internes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cree le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis a jour le"),
                ),
            ],
            options={
                "verbose_name": "Regle pricing abonnement",
                "verbose_name_plural": "Regles pricing abonnement",
                "ordering": ["pack", "taille_sac"],
                "unique_together": {("pack", "taille_sac")},
            },
        ),
    ]
