# Generated by Django 5.0.7 on 2026-07-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0085_abonnement_abonnementpricingrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_origin",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("routine_trial", "Essai Routine"),
                    ("backoffice", "Cree par OPS"),
                    ("migration", "Migration/import"),
                ],
                default="normal",
                max_length=30,
                verbose_name="Origine de la commande",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="routine_choisie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Solo"),
                    ("duo", "Duo"),
                    ("famille", "Famille"),
                    ("business", "Business"),
                ],
                default="",
                help_text="Peut differer de routine_proposee si le client corrige la recommandation.",
                max_length=20,
                verbose_name="Routine finalement choisie par le client",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="routine_proposee",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Solo"),
                    ("duo", "Duo"),
                    ("famille", "Famille"),
                    ("business", "Business"),
                ],
                default="",
                help_text="Jamais modifiee apres creation - trace la recommandation initiale du moteur.",
                max_length=20,
                verbose_name="Routine proposee par le diagnostic",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="satisfaction_contactee_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Client contacte le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="satisfaction_reponse",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("positive", "Positive"),
                    ("incident", "Incident signale"),
                    ("resolved", "Incident resolu"),
                    ("negative", "Negative"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Reponse satisfaction",
            ),
        ),
    ]
