# Generated by Django 5.0.7 on 2026-07-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0086_order_order_origin_order_routine_choisie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="essai_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Commande d'essai a l'origine de cet abonnement, si applicable - jamais modifie retroactivement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abonnements_convertis",
                to="orders.order",
            ),
        ),
        migrations.CreateModel(
            name="EvenementRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("diagnostic_commence", "Diagnostic commence"),
                            ("diagnostic_termine", "Diagnostic termine"),
                            ("routine_recommandee", "Routine recommandee"),
                            ("routine_changee", "Routine changee"),
                            ("essai_reserve", "Essai reserve"),
                            ("essai_paye", "Essai paye"),
                            ("essai_livre", "Essai livre"),
                            ("satisfaction_confirmee", "Satisfaction confirmee"),
                            ("abonnement_propose", "Abonnement propose"),
                            ("abonnement_accepte", "Abonnement accepte"),
                            ("abonnement_active", "Abonnement active"),
                        ],
                        max_length=40,
                        verbose_name="Type",
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(blank=True, default=dict, verbose_name="Donnees"),
                ),
                (
                    "horodatage",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodate le"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evenement Routine",
                "verbose_name_plural": "Evenements Routine",
                "ordering": ["-horodatage"],
            },
        ),
    ]
