# Generated by Django 5.0.7 on 2026-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0087_abonnement_essai_origine_evenementroutine"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnementpricingrule",
            name="prix_mensuel",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix reellement facture pour l'abonnement (4 collectes hebdomadaires) - source de verite pour la facturation reelle. Distinct du prix hebdomadaire indicatif.",
                max_digits=10,
                verbose_name="Prix mensuel (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="taille_sac",
            field=models.CharField(
                choices=[("S", "Sac S"), ("M", "Sac M"), ("XL", "Sac XL")],
                max_length=2,
                verbose_name="Taille sac",
            ),
        ),
        migrations.AlterField(
            model_name="abonnementpricingrule",
            name="prix_hebdomadaire",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix indicatif par collecte - utilise pour l'essai ponctuel (une seule collecte, pas d'engagement).",
                max_digits=10,
                verbose_name="Prix hebdomadaire (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="abonnementpricingrule",
            name="taille_sac",
            field=models.CharField(
                choices=[("S", "Sac S"), ("M", "Sac M"), ("XL", "Sac XL")],
                max_length=2,
                verbose_name="Taille sac",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="bag_size",
            field=models.CharField(
                choices=[("S", "Sac S"), ("M", "Sac M"), ("XL", "Sac XL")],
                default="M",
                max_length=2,
                verbose_name="Taille sac",
            ),
        ),
    ]
