# Generated by Django 5.0.7 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0088_abonnementpricingrule_prix_mensuel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_normalized",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro (normalisé)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Note interne"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Numéro autorisé (pilote)",
                "verbose_name_plural": "Liste blanche du pilote",
                "ordering": ["-created_at"],
            },
        ),
    ]
