# Generated by Django 5.0.7 on 2026-08-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0089_pilotwhitelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wave_checkout_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Session Checkout Wave créée le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wave_checkout_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=120,
                verbose_name="ID session Checkout Wave",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wave_checkout_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="URL session Checkout Wave",
            ),
        ),
    ]
