# Generated by Django 5.0.7 on 2026-08-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0090_wave_checkout_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fagnievent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order.created", "Commande créée"),
                    ("payment.paid", "Paiement reçu"),
                    ("pickup.assigned", "Livreur collecte assigné"),
                    ("pickup.started", "Collecte démarrée"),
                    (
                        "pickup.done",
                        "Collecte confirmée (legacy, conserve pour historique)",
                    ),
                    ("pickup.collected", "Collecte confirmée"),
                    ("pressing.received", "Pressing reçu"),
                    ("pressing.done", "Pressing terminé"),
                    ("delivery.assigned", "Livreur livraison assigné"),
                    ("delivery.started", "Livraison démarrée"),
                    ("delivery.done", "Livraison confirmée"),
                    ("order.cancelled", "Commande annulée"),
                    ("incident.reported", "Incident signalé"),
                ],
                db_index=True,
                max_length=60,
                verbose_name="Événement",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("in_progress", "En cours"),
                    ("ready", "Prêt"),
                    ("done", "Terminée"),
                    ("canceled", "Annulée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
