# Generated by Django 5.0.7 on 2026-08-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0092_payment_accounting_status_and_void_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpaymentevent",
            name="channel",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet"),
                    ("wallet_auto", "Wallet automatique"),
                    ("wave_webhook", "Wave webhook"),
                    ("wave_ops", "Wave OPS vérifié API"),
                    ("wave_manual_verified", "Wave vérifié manuellement"),
                    ("cash", "Cash"),
                    ("manual", "Manuel"),
                ],
                default="manual",
                max_length=30,
                verbose_name="Canal",
            ),
        ),
    ]
