# Generated by Django 5.0.7 on 2026-09-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd", "0001_initial_crowd_models"),
        ("orders", "0093_alter_orderpaymentevent_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryleg",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("professional", "Livreur professionnel"),
                    ("cotransporter", "Cotransporteur"),
                ],
                default="professional",
                help_text="professional = DeliveryPartner, cotransporter = Cotransporter",
                max_length=20,
                verbose_name="Type d'acteur",
            ),
        ),
        migrations.AddField(
            model_name="deliveryleg",
            name="cotransporter",
            field=models.ForeignKey(
                blank=True,
                help_text="Rempli uniquement si actor_type='cotransporter'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_legs",
                to="crowd.cotransporter",
                verbose_name="Cotransporteur",
            ),
        ),
    ]
