# Generated by Django 5.0.7 on 2026-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0094_add_crowd_fields_to_deliveryleg"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryleg",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/heure d'acceptation par le cotransporteur",
                null=True,
                verbose_name="Offre acceptée le",
            ),
        ),
        migrations.AddField(
            model_name="deliveryleg",
            name="assignment_reason",
            field=models.CharField(
                blank=True,
                help_text="Code standardisé (MATCHED, DETOUR_TOO_HIGH, etc.)",
                max_length=100,
                verbose_name="Raison d'assignation",
            ),
        ),
        migrations.AddField(
            model_name="deliveryleg",
            name="assignment_source",
            field=models.CharField(
                choices=[
                    ("crowd", "Crowd (Cotransporteur)"),
                    ("professional", "Professionnel"),
                    ("manual", "Manuel (OPS)"),
                    ("ops", "OPS (non assigné)"),
                ],
                default="professional",
                help_text="Qui a assigné cette jambe",
                max_length=20,
                verbose_name="Source d'assignation",
            ),
        ),
        migrations.AddField(
            model_name="deliveryleg",
            name="offer_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/heure d'expiration de l'offre Crowd",
                null=True,
                verbose_name="Offre expire le",
            ),
        ),
        migrations.AddField(
            model_name="deliveryleg",
            name="offered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/heure de l'offre Crowd (si applicable)",
                null=True,
                verbose_name="Offre envoyée le",
            ),
        ),
    ]
