# Generated by Django 5.0.7 on 2026-09-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0095_add_crowd_traceability_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcmtoken",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("driver", "Livreur"),
                    ("partner", "Pressing"),
                    ("ops", "OPS"),
                    ("cotransporter", "Cotransporteur"),
                ],
                max_length=20,
            ),
        ),
    ]
